### PR TITLE
Update tlg2042.tlg084.opp-grc1.xml

### PR DESCRIPTION
**Pull request by AlisonBabeu**
Added in editor info
Added in language tagging
Updated bibliographic info

### CODE REVIEW

**Comment by capitains-hook** [comment]
*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/160)*

**Comment by capitains-hook** [comment]
*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/162)*

**Comment by planatheisa** [comment]
Is it `xml:lang="deu"` or `xml:lang="ger"` ? I have seen both recently and I always thought "ger" to be the "right" one. @AlisonBabeu

**Comment by sonofmun** [comment]
If you look here (http://www-01.sil.org/iso639-3/codes.asp?order=639_3&letter=d), the correct ISO 639-3 code for German is "deu". We should try to be consistent when using this, correcting it when we see a problem. Though, in the end, both will be correctly understood since there is no "ger" code in the 639-3 standard.

**Pull request merged**
