### PR TITLE
Added tlg1765.tlg005.First1K-grc1.xml Βιβλίον μυθικὸν τοῦ Αἰσώπου

### PR DESCRIPTION
**Pull request by sonofmun**

### CODE REVIEW

**Comment by sonofmun** [comment]
Finally passes Hook. Please check and merge @annettegessner

**Comment by sonofmun** [comment]
Still passes. Can be merged.

**Comment by annettegessner** [comment]
LangUsage should be Greek only, level of citation is "book" in the header and "chapter" in the text. The one chaper is n="5", but it's called "III". Just one div is ok, for it's very short.

**Comment by sonofmun** [comment]
And the `<div>` for the chapter level is @type="edition" instead of @type="textpart". I must have been really tired when I did this file. I will fix it next week.

**Comment by sonofmun** [comment]
Fixed the problems and it still passes. Please check and merge @annettegessner or @planatheisa

**Comment by planatheisa** [comment]
@sonofmun  Is this the right schema? It's different than in other files.

**Comment by sonofmun** [comment]
How is it different?

**Comment by planatheisa** [comment]
`<?oxygen RNGSchema="http://www.stoa.org/epidoc/schema/latest/tei-epidoc.rng" type="xml"?>` vs. `<?xml-model href="http://www.stoa.org/epidoc/schema/latest/tei-epidoc.rng" schematypens="http://relaxng.org/ns/structure/1.0"?>`

**Comment by sonofmun** [comment]
This one should be ready to merge as well, @planatheisa

**Comment by planatheisa** [comment]
Why does the CTS say "book" but the div type="chapter" n="5" ? Sorry I didn't notice earlier.

**Comment by sonofmun** [comment]
It was an oversight on my part. I have corrected the cRefPattern to match the `<div>` element.

**Pull request merged**
