### PR TITLE
Added tlg2178.tlg001

### PR DESCRIPTION
**Pull request by planatheisa**
Checking Hook.

### CODE REVIEW

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +2 |
| `metadata_total`   |       +2 |
| `nodes_count`      |       +6 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |    +5476 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg2178/__cts__.xml`                          | New      |
| `./data/tlg2178/tlg001/__cts__.xml`                   | New      |
| `./data/tlg2178/tlg001/tlg2187.tlg001.1st1K-grc1.xml` | New      |
| `./data/tlg2178/__cts__.xml`                          | Passing  |
| `./data/tlg2178/tlg001/__cts__.xml`                   | Passing  |
| `./data/tlg2178/tlg001/tlg2187.tlg001.1st1K-grc1.xml` | Failing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/3749)*

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +2 |
| `metadata_total`   |       +2 |
| `nodes_count`      |       +6 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |    +5476 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg2178/__cts__.xml`                          | New      |
| `./data/tlg2178/tlg001/__cts__.xml`                   | New      |
| `./data/tlg2178/tlg001/tlg2187.tlg001.1st1K-grc1.xml` | New      |
| `./data/tlg2178/__cts__.xml`                          | Passing  |
| `./data/tlg2178/tlg001/__cts__.xml`                   | Passing  |
| `./data/tlg2178/tlg001/tlg2187.tlg001.1st1K-grc1.xml` | Failing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/3752)*

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +2 |
| `metadata_total`   |       +2 |
| `nodes_count`      |       +6 |
| `texts_passing`    |       +1 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |    +5476 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg2178/__cts__.xml`                          | New      |
| `./data/tlg2178/tlg001/__cts__.xml`                   | New      |
| `./data/tlg2178/tlg001/tlg2178.tlg001.1st1K-grc1.xml` | New      |
| `./data/tlg2178/__cts__.xml`                          | Passing  |
| `./data/tlg2178/tlg001/__cts__.xml`                   | Passing  |
| `./data/tlg2178/tlg001/tlg2178.tlg001.1st1K-grc1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/3758)*

**Comment by planatheisa** [comment]
Since I can't, I'll just go ahead and do it. Seems prudent anyway.

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +2 |
| `metadata_total`   |       +2 |
| `nodes_count`      |      +31 |
| `texts_passing`    |       +1 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |    +5476 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg2178/__cts__.xml`                          | New      |
| `./data/tlg2178/tlg001/__cts__.xml`                   | New      |
| `./data/tlg2178/tlg001/tlg2178.tlg001.1st1K-grc1.xml` | New      |
| `./data/tlg2178/__cts__.xml`                          | Passing  |
| `./data/tlg2178/tlg001/__cts__.xml`                   | Passing  |
| `./data/tlg2178/tlg001/tlg2178.tlg001.1st1K-grc1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/3802)*

**Pull request merged**
