### PR TITLE
Added Lucian Phalaris

### PR DESCRIPTION
**Pull request by sonofmun**

### CODE REVIEW

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +2 |
| `metadata_total`   |       +2 |
| `nodes_count`      |      +29 |
| `texts_passing`    |       +1 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |    +2920 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg0062/tlg001/__cts__.xml`                   | New      |
| `./data/tlg0062/tlg001/tlg0062.tlg001.1st1K-grc1.xml` | New      |
| `./data/tlg0087/tlg034/__cts__.xml`                   | New      |
| `./data/tlg0062/tlg001/__cts__.xml`                   | Passing  |
| `./data/tlg0062/tlg001/tlg0062.tlg001.1st1K-grc1.xml` | Passing  |
| `./data/tlg0087/tlg034/__cts__.xml`                   | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/2428)*

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +1 |
| `metadata_total`   |       +1 |
| `nodes_count`      |      +29 |
| `texts_passing`    |       +1 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |    +2920 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg0062/tlg001/__cts__.xml`                   | New      |
| `./data/tlg0062/tlg001/tlg0062.tlg001.1st1K-grc1.xml` | New      |
| `./data/tlg0062/tlg001/__cts__.xml`                   | Passing  |
| `./data/tlg0062/tlg001/tlg0062.tlg001.1st1K-grc1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/2429)*

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +1 |
| `metadata_total`   |       +1 |
| `nodes_count`      |      +29 |
| `texts_passing`    |       +1 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |    +2920 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg0062/tlg001/__cts__.xml`                   | New      |
| `./data/tlg0062/tlg001/tlg0062.tlg001.1st1K-grc1.xml` | New      |
| `./data/tlg0062/tlg001/__cts__.xml`                   | Passing  |
| `./data/tlg0062/tlg001/tlg0062.tlg001.1st1K-grc1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/2432)*

**Comment by planatheisa** [comment]
Alternately, maybe the title should get a "lat".

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +1 |
| `metadata_total`   |       +1 |
| `nodes_count`      |      +29 |
| `texts_passing`    |       +1 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |    +2920 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg0062/tlg001/__cts__.xml`                   | New      |
| `./data/tlg0062/tlg001/tlg0062.tlg001.1st1K-grc1.xml` | New      |
| `./data/tlg0062/tlg001/__cts__.xml`                   | Passing  |
| `./data/tlg0062/tlg001/tlg0062.tlg001.1st1K-grc1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/2532)*

**Pull request merged**
