### PR TITLE
Added tlg1764.tlg001

### PR DESCRIPTION
**Pull request by planatheisa**

### CODE REVIEW

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +3 |
| `metadata_total`   |       +3 |
| `nodes_count`      |     +321 |
| `texts_passing`    |       +1 |
| `texts_total`      |       +2 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |  +106499 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg0559/tlg014/__cts__.xml`                   | New      |
| `./data/tlg0559/tlg014/tlg0559.tlg014.1st1K-grc1.xml` | New      |
| `./data/tlg1764/__cts__.xml`                          | New      |
| `./data/tlg1764/tlg001/__cts__.xml`                   | New      |
| `./data/tlg1764/tlg001/tlg1764.tlg001.1st1K-grc1.xml` | New      |
| `./data/tlg0559/tlg014/__cts__.xml`                   | Passing  |
| `./data/tlg0559/tlg014/tlg0559.tlg014.1st1K-grc1.xml` | Passing  |
| `./data/tlg1764/__cts__.xml`                          | Passing  |
| `./data/tlg1764/tlg001/__cts__.xml`                   | Passing  |
| `./data/tlg1764/tlg001/tlg1764.tlg001.1st1K-grc1.xml` | Failing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/3835)*

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +3 |
| `metadata_total`   |       +3 |
| `nodes_count`      |     +321 |
| `texts_passing`    |       +2 |
| `texts_total`      |       +2 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |  +106499 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg0559/tlg014/__cts__.xml`                   | New      |
| `./data/tlg0559/tlg014/tlg0559.tlg014.1st1K-grc1.xml` | New      |
| `./data/tlg1764/__cts__.xml`                          | New      |
| `./data/tlg1764/tlg001/__cts__.xml`                   | New      |
| `./data/tlg1764/tlg001/tlg1764.tlg001.1st1K-grc1.xml` | New      |
| `./data/tlg0559/tlg014/__cts__.xml`                   | Passing  |
| `./data/tlg0559/tlg014/tlg0559.tlg014.1st1K-grc1.xml` | Passing  |
| `./data/tlg1764/__cts__.xml`                          | Passing  |
| `./data/tlg1764/tlg001/__cts__.xml`                   | Passing  |
| `./data/tlg1764/tlg001/tlg1764.tlg001.1st1K-grc1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/3838)*

**Comment by sonofmun** [comment]
The chapters are really long here. I think we should add another citation layer at the paragraph level.

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +2 |
| `metadata_total`   |       +2 |
| `nodes_count`      |     +848 |
| `texts_passing`    |       +1 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |  +103966 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg1764/__cts__.xml`                          | New      |
| `./data/tlg1764/tlg001/__cts__.xml`                   | New      |
| `./data/tlg1764/tlg001/tlg1764.tlg001.1st1K-grc1.xml` | New      |
| `./data/tlg1764/__cts__.xml`                          | Passing  |
| `./data/tlg1764/tlg001/__cts__.xml`                   | Passing  |
| `./data/tlg1764/tlg001/tlg1764.tlg001.1st1K-grc1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/3852)*

**Pull request merged**
