### PR TITLE
Update tlg5034.tlg001c.perseus-grc1.xml

### PR DESCRIPTION
**Pull request by PRoryCallahan**
1.) Removed extraneous page number notes. 2.) Removed extra returns 3.) Made consistent paragraph tags to all scholia (a., b., etc.) 4.) Moved MS notations from OCR position to where Drachmann intended to be read in text 5.) few line breaks should have been paragraph and vice versa 6.) caught incorrect line #s 7.) added some elements in Drachmann that were missing in scan 8.) deleted portions that were scans of app. crit.

### CODE REVIEW

**Comment by PRoryCallahan** [comment]
I'm not sure why the build is failing. It had successfully passed Hook Test before I committed the pull request. XML is valid.

**Comment by lcerrato** [comment]
@PRoryCallahan 
We are having issues throughout all repositories. It is a problem in our continuous integration setup.
I am working to identify the downstream issues — I think we are depending on a server that was inaccessible and has just been restored. Bear with us!

**Comment by PRoryCallahan** [comment]
Thanks @lcerrato. When I looked at the Travis report that's what I suspected. Glad to see that whatever was going on has cleared up!

**Review by lcerrato — APPROVED** [review]

**Comment by lcerrato** [comment]
@PRoryCallahan 
Thank you!

**Pull request merged**
