### PR TITLE
Added tlg2039.tlg004.1st1K-grc1.xml

### PR DESCRIPTION
**Pull request by sonofmun**
Diaphantus Alexandrinus Fragmentum [Sp.] (e cod. Paris. 453)

### CODE REVIEW

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +2 |
| `metadata_total`   |       +2 |
| `nodes_count`      |      +26 |
| `texts_passing`    |       +1 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |    +2519 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg2039/__cts__.xml`                          | New      |
| `./data/tlg2039/tlg004/__cts__.xml`                   | New      |
| `./data/tlg2039/tlg004/tlg2039.tlg004.1st1K-grc1.xml` | New      |
| `./data/tlg2039/__cts__.xml`                          | Passing  |
| `./data/tlg2039/tlg004/__cts__.xml`                   | Passing  |
| `./data/tlg2039/tlg004/tlg2039.tlg004.1st1K-grc1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/2222)*

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +2 |
| `metadata_total`   |       +2 |
| `nodes_count`      |      +26 |
| `texts_passing`    |       +1 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |    +2519 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg2039/__cts__.xml`                          | New      |
| `./data/tlg2039/tlg004/__cts__.xml`                   | New      |
| `./data/tlg2039/tlg004/tlg2039.tlg004.1st1K-grc1.xml` | New      |
| `./data/tlg2039/__cts__.xml`                          | Passing  |
| `./data/tlg2039/tlg004/__cts__.xml`                   | Passing  |
| `./data/tlg2039/tlg004/tlg2039.tlg004.1st1K-grc1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/2225)*

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +2 |
| `metadata_total`   |       +2 |
| `nodes_count`      |      +26 |
| `texts_passing`    |       +1 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |    +2519 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg2039/__cts__.xml`                          | New      |
| `./data/tlg2039/tlg004/__cts__.xml`                   | New      |
| `./data/tlg2039/tlg004/tlg2039.tlg004.1st1K-grc1.xml` | New      |
| `./data/tlg2039/__cts__.xml`                          | Passing  |
| `./data/tlg2039/tlg004/__cts__.xml`                   | Passing  |
| `./data/tlg2039/tlg004/tlg2039.tlg004.1st1K-grc1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/2235)*

**Comment by annettegessner** [comment]
Two things:
1) This file also contains another fragment (fragment 1), which has according to the Perseus Catalog another URN than this one, so I guess it should be divided. Fragment 2 is the correct one for this file, fragment 1 should be "Fragmentum [Sp.] --(e cod. Paris. suppl. gr. 387, fol. 181r)", URN: urn:cts:greekLit:tlg2039.tlg003 .

2) There are some mathematical graphs in this (e.g. here: https://babel.hathitrust.org/cgi/pt?id=njp.32101054395205;view=2up;seq=554 ). Shall we write a ticket, so somebody can address this issue at some point?

**Comment by sonofmun** [comment]
@annettegessner You're right. I completely missed that the first and second fragments have different URNs. I will separate them from each other. And then we should put an issue in to insert the placeholders for the graphs.

**Comment by sonofmun** [comment]
@annettegessner This should be fixed now. Take a look.

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +3 |
| `metadata_total`   |       +3 |
| `nodes_count`      |      +29 |
| `texts_passing`    |       +2 |
| `texts_total`      |       +2 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |    +2621 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg2039/__cts__.xml`                          | New      |
| `./data/tlg2039/tlg003/__cts__.xml`                   | New      |
| `./data/tlg2039/tlg003/tlg2039.tlg003.1st1K-grc1.xml` | New      |
| `./data/tlg2039/tlg004/__cts__.xml`                   | New      |
| `./data/tlg2039/tlg004/tlg2039.tlg004.1st1K-grc1.xml` | New      |
| `./data/tlg2039/__cts__.xml`                          | Passing  |
| `./data/tlg2039/tlg003/__cts__.xml`                   | Passing  |
| `./data/tlg2039/tlg003/tlg2039.tlg003.1st1K-grc1.xml` | Passing  |
| `./data/tlg2039/tlg004/__cts__.xml`                   | Passing  |
| `./data/tlg2039/tlg004/tlg2039.tlg004.1st1K-grc1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/2244)*

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +3 |
| `metadata_total`   |       +3 |
| `nodes_count`      |      +29 |
| `texts_passing`    |       +2 |
| `texts_total`      |       +2 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |    +2621 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg2039/__cts__.xml`                          | New      |
| `./data/tlg2039/tlg003/__cts__.xml`                   | New      |
| `./data/tlg2039/tlg003/tlg2039.tlg003.1st1K-grc1.xml` | New      |
| `./data/tlg2039/tlg004/__cts__.xml`                   | New      |
| `./data/tlg2039/tlg004/tlg2039.tlg004.1st1K-grc1.xml` | New      |
| `./data/tlg2039/__cts__.xml`                          | Passing  |
| `./data/tlg2039/tlg003/__cts__.xml`                   | Passing  |
| `./data/tlg2039/tlg003/tlg2039.tlg003.1st1K-grc1.xml` | Passing  |
| `./data/tlg2039/tlg004/__cts__.xml`                   | Passing  |
| `./data/tlg2039/tlg004/tlg2039.tlg004.1st1K-grc1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/2247)*

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +3 |
| `metadata_total`   |       +3 |
| `nodes_count`      |      +29 |
| `texts_passing`    |       +2 |
| `texts_total`      |       +2 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |    +2621 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg2039/__cts__.xml`                          | New      |
| `./data/tlg2039/tlg003/__cts__.xml`                   | New      |
| `./data/tlg2039/tlg003/tlg2039.tlg003.1st1K-grc1.xml` | New      |
| `./data/tlg2039/tlg004/__cts__.xml`                   | New      |
| `./data/tlg2039/tlg004/tlg2039.tlg004.1st1K-grc1.xml` | New      |
| `./data/tlg2039/__cts__.xml`                          | Passing  |
| `./data/tlg2039/tlg003/__cts__.xml`                   | Passing  |
| `./data/tlg2039/tlg003/tlg2039.tlg003.1st1K-grc1.xml` | Passing  |
| `./data/tlg2039/tlg004/__cts__.xml`                   | Passing  |
| `./data/tlg2039/tlg004/tlg2039.tlg004.1st1K-grc1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/2249)*

**Comment by annettegessner** [comment]
I guess we could drop the "fragment" now and only have paragraphs in the refsDecl. However we decide, we should have it the same way in the third fragment. Otherwise all good to go!

**Comment by sonofmun** [comment]
True. I will do that. It should speed up the testing and text retrieval process.

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +3 |
| `metadata_total`   |       +3 |
| `nodes_count`      |      +24 |
| `texts_passing`    |       +2 |
| `texts_total`      |       +2 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |    +2521 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg2039/__cts__.xml`                          | New      |
| `./data/tlg2039/tlg003/__cts__.xml`                   | New      |
| `./data/tlg2039/tlg003/tlg2039.tlg003.1st1K-grc1.xml` | New      |
| `./data/tlg2039/tlg004/__cts__.xml`                   | New      |
| `./data/tlg2039/tlg004/tlg2039.tlg004.1st1K-grc1.xml` | New      |
| `./data/tlg2039/__cts__.xml`                          | Passing  |
| `./data/tlg2039/tlg003/__cts__.xml`                   | Passing  |
| `./data/tlg2039/tlg003/tlg2039.tlg003.1st1K-grc1.xml` | Passing  |
| `./data/tlg2039/tlg004/__cts__.xml`                   | Passing  |
| `./data/tlg2039/tlg004/tlg2039.tlg004.1st1K-grc1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/2252)*

**Comment by sonofmun** [comment]
If it still looks good, @annettegessner , go ahead and merge it.

**Pull request merged**
