### PR TITLE
Tlg0559.tlg012

### PR DESCRIPTION
**Pull request by sonofmun**

### CODE REVIEW

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +2 |
| `metadata_total`   |       +2 |
| `nodes_count`      |      +49 |
| `texts_passing`    |       +1 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |    +5399 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg0559/__cts__.xml`                          | New      |
| `./data/tlg0559/tlg012/__cts__.xml`                   | New      |
| `./data/tlg0559/tlg012/tlg0559.tlg012.1st1K-grc1.xml` | New      |
| `./data/tlg0559/__cts__.xml`                          | Passing  |
| `./data/tlg0559/tlg012/__cts__.xml`                   | Passing  |
| `./data/tlg0559/tlg012/tlg0559.tlg012.1st1K-grc1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/3703)*

**Comment by AlisonBabeu** [comment]
Hi @sonofmun one tiny issue, in the CTS edition title you have the editor name in the middle of the title:
```xml
 <ti:description xml:lang="mul">Hero of Alexandria, Belopoeica, Marsden, Greek and Roman Artillery: Technical Treatises, Clarendon, 1971</ti:description>
```

**Comment by sonofmun** [comment]
The work name is Belopoeica and it comes from the volume by Marsden called "Greek and Roman Artillery: Technical Treatises", which includes other treatises by other authors (though I don't know which ones). Maybe there is a better way to make this clear in the metadata file?

**Comment by planatheisa** [comment]
What if you put the title in brackets: `Marsden (Greek and Roman Artillery...)`, so they are on a different level than the other items? If we add this title then shouldn't we do this for all books which contain works from several authors? In that case, maybe it would be better to add a space for the book title as well. Also, wasn't the cts structure going to change anyway into something more detailed? I seem to remember something like that from last year.

**Comment by sonofmun** [comment]
That's a good idea. And yes we had discussed adding DC (or some other) metadata as well. We just have never gotten around to it.

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +1 |
| `metadata_total`   |       +1 |
| `nodes_count`      |      +49 |
| `texts_passing`    |       +1 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |    +5399 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg0559/tlg012/__cts__.xml`                   | New      |
| `./data/tlg0559/tlg012/tlg0559.tlg012.1st1K-grc1.xml` | New      |
| `./data/tlg0559/tlg012/__cts__.xml`                   | Passing  |
| `./data/tlg0559/tlg012/tlg0559.tlg012.1st1K-grc1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/3783)*

**Pull request merged**
