### PR TITLE
#643: corrected header, CTS, langUsage and divs, added cts files and …

### PR DESCRIPTION
**Pull request by planatheisa**
…reference

First upload, checking hook.

### CODE REVIEW

**Comment by sonofmun** [comment]
Could you add the following after the `</mongr>` element in the header (at line 60):

    <ref target="https://archive.org/details/ecclesiasticalhi00evag">Internet Archive</ref>

**Comment by planatheisa** [comment]
I thought I had, will do.

**Comment by planatheisa** [comment]
Forgot to save.

**Comment by sonofmun** [comment]
Still passes. Merging.

**Pull request merged**
