### PR TITLE
update tlg5034.tlg001a

### PR DESCRIPTION
**Pull request by PRoryCallahan**
Last one of the Pindar scholia. For my project, I am also going to use the Perseus Pindar (tlg0033) as the base text before making edits/modifications. If I catch anything needing correction, should I be looking at https://github.com/PerseusDL/canonical-greekLit/tree/master/data/tlg0033 for pull requests?

e.g. I see that the title to the Pythian odes are transcribed as πψτηιαν which also displays on Scaife.

Also, super humbling to see change records in those docs going back to the late 80s.

### CODE REVIEW

**Comment by PRoryCallahan** [comment]
@lcerrato That's good to know. Is there a blank template with preferred headers and metadata that I should use for reference? Or should I just infer from the OpenGreekAndLatin files?

**Review by lcerrato — APPROVED** [review]

**Comment by lcerrato** [comment]
@PRoryCallahan 
There is an OGL header template but not a Perseus one as we do the header and metadata reviews in house. Every collection/author in Perseus has work and file specific inconsistencies that I can't determine until I am actually in the files. The older the works, the more likely they are to need a careful review.
If you would prefer to open an issue with some things you have noticed, we can then address them in the context of a text review. Otherwise, @AlisonBabeu  and I will review in a separate pass as we each work on different elements.

**Comment by PRoryCallahan** [comment]
@lcerrato 
All of this is helpful. I can go back and re-insert the page breaks. Looking back, would you like me to make the numbering consistent? That is, one records volume number before page number and another doesn't, e.g. Olympians = <pb  n="1.198"/> vs. Nemeans = <pb n="198"/>. Which would you prefer as I retag these?

Since we are looking to go back and make it maximally representative of the printed text, should I go back and make <p> tags consistent with where Drachmann breaks paragraphs?

Here is an example (urn:cts:greekLit:tlg5034.tlg001b.perseus-grc1:4:427):

<div type="textpart" subtype="line" n="427">
	<p><note n="BDEGQ"/>a. ποίας ἔρεπτον: κυρίως τὸ ἐρέπτειν ἐπὶ τῶν ἀλόγων ζῴων τάττεται, ὅτι ἐπὶ τῇ ἔρᾳ, τουτέστι τῇ γῇ ἐσθίουσιν. ὡς Ὅμηρος (Θ 560)· <lb/>ἵπποι δὲ κρῖ λευκὸν ἐρεπτόμενοι καὶ ὀλύρας. νῦν δὲ ἀντὶ τοῦ ἔρεφον ἔλαβε, τουτέστιν ἐστέγουν, ἐστεφάνουν. <note n="5"/> 428 B</p>
	<p>b. ἄλλως· τὸ παλαιὸν ἐφυλλοβόλουν τοὺς νικηφόρους τοῖς τῆς γῆς χλωροῖς. 427 a B</p>
</div>

-----
My questions:

1.) <lb/>ἵπποι δὲ κρῖ λευκὸν ἐρεπτόμενοι καὶ ὀλύρας. I would expect to be enclosed in <quote>. Should I enclose these block quotes in some other manner than with <lb/>? If not, should I do something to indicate the end of the quote and resumption of the main text?

2.) <p>b. ἄλλως· τὸ παλαιὸν ἐφυλλοβόλουν τοὺς νικηφόρους τοῖς τῆς γῆς χλωροῖς. 427 a B</p> in the physical text should be enclosed in the same <p> as 427 a. i.e. 

<p><note n="BDEGQ"/>a. ποίας ἔρεπτον: κυρίως τὸ ἐρέπτειν ἐπὶ τῶν ἀλόγων ζῴων τάττεται, ὅτι ἐπὶ τῇ ἔρᾳ, τουτέστι τῇ γῇ ἐσθίουσιν. ὡς Ὅμηρος (Θ 560)· <lb/>ἵπποι δὲ κρῖ λευκὸν ἐρεπτόμενοι καὶ ὀλύρας. νῦν δὲ ἀντὶ τοῦ ἔρεφον ἔλαβε, τουτέστιν ἐστέγουν, ἐστεφάνουν. <note n="5"/> 428 B b. ἄλλως· τὸ παλαιὸν ἐφυλλοβόλουν τοὺς νικηφόρους τοῖς τῆς γῆς χλωροῖς. 427 a B</p>

Would you like me to resolve these within the same <p> or would you like represented each individual scholion by its own <p>?

**Comment by lcerrato** [comment]
@PRoryCallahan 
I did not notice this in other reviews — a major drawback of a large file PR. 
My goal in reviewing this was really just to make sure the text continues to meet the EpiDoc/CTS requirements as I figured we had something very basic and it could only get better from there! :)

I've already started with page breaks, so no need to go back now. How these are/are not numbered is not consistent across the collection. As long as it makes sense and permits editors to find the pages, including or excluding volumes is unimportant. (I usually only see out where one file is a merged version of several volumes. There it is important.) Most new page numbers include the whole file identifier, so there is not one standard. It's entirely up to the editor.

I was noticing other deleted text where some of the main text was incorrectly included in notes and then went missing. 
I'm presuming these were moved, based on your change log? (This is a challenge for diffing the files and I have noticed text that was part of the `<note>` tags that should not have been there. I also found a page where it seemed unusually short — where it looked to me as if there was missing text. 

I would have to do a deep dive to answer about further enhancements in your questions here since I am not familiar with the work. I'm not a subject expert. I generally follow the conventions in similar OGL texts (in this case, scholia) and the TLG. 
Every text is different and I can't quickly advise on structural issues without more research. The best examples we have are usually going to be other texts as there is just no way right now to create a markup document that covers all of the various types of files (and keep doing the work itself!).

There are things we would typically enhance that I see as I go through this. For instance, where you have line breaks, these are generally block quotes, and I also see untagged English (Latin?) mixed in with Greek. We also try to include indentation and so forth, again, for ease of reading and consistency with the print.  These are just superficial things that I see when I look at the page breaks, so I would need more time to make additional recommendations.

I don't ask those who graciously volunteer to make fixes (as you've done) to do that sort of file cleanup/enhancement as it's not critical to the presentation, time consuming, and something we can have reviewed later on. 

This is a challenge of having several different streams of data entry managed at different phases of work by different people and trying to retroactively impose a more consistent level of markup on large and complex works. The first push of OGL data was to get basic versions of missing texts.

**Comment by lcerrato** [comment]
@PRoryCallahan 

1. A blockquote would be `<quote type="blockquote">` with either `<l>` tags wrapping a multiline selection or `<lb/>` appearing at the end of any interior lines only. Any further indentation within the blockquote itself can be indicated by adding the attributes to those tags as needed. (A quotation indicated by single or double quotation marks is `<q>`.)2. 

2. For the structure:— Ideally, yes, each would be it's own reference.3. or some the current scholia, I see divisions such as work/line/part (for a text that has multiple works) or line/part.or some the current scholia, I see divisions such as work/line/part (for a text that has multiple works) or line/part.
So, in brief, this would probably be structured along the lines of poem/line/part where the parts are the small Roman letters.

Here is an example:

```
<div type="textpart" subtype="work" xml:base="urn:cts:greekLit:tlg5023.tlg001.1st1K-grc1" n="sch_Hec"> 
<head rend="center">ΣΧΟΛΙΑ ΕΙΣ ΕΚΑΒΗΝ</head> 
<div type="textpart" subtype="line" xml:base="urn:cts:greekLit:tlg5023.tlg001.1st1K-grc1:sch_Hec" n="1"> 
<div type="textpart" subtype="part" xml:base="urn:cts:greekLit:tlg5023.tlg001.1st1K-grc1:sch_Hec.1" n="1"> 
<p rend="indent">....
```
a. Here the **work = sch_Hec**; for this text the equivalent would be **poem**, and since these are all the same set, the digit is fine. (=4 in your above example).
b. **line=line**. This holds here. (=427)
c. **part** is inexact — there's not a great equivalent (perhaps, "instance"?). In this work, we have a, b, c, etc.
d. **<p>** to distinguish where a new indentation occurs, you'd have <p rend="indent">. So, on page 305, I see that 9.162a, 162c, 162d have indentation but 162b does not. The indent attribute allows for maintaining the print distinction.




If letters or digits are preserved (as opposed to being captured only in the divs), these should be labels. This is important for the letters, which should be `<label xml:lang="eng">`.

The witnesses (?) in the margins would preferably be with each corresponding part (perhaps at the beginning?) rather than where they appear in print. (Something like `<note place="marginal" type="witness" xml:lang="eng/lat">BCDEQ</note>`.) This would enable the preservation of the footnotes as something distinct.

When the witnesses appear in the body of the text, we have `<ref type="witness">` and we have `<bibl>` for citations.

**Comment by lcerrato** [comment]
I should also add that the above recommendations don't work when you get to book page 340-1 and you have **10.117a, 117b, 117**!
In that case, we're left with something like "x" to represent a whole line scholium.
(This is why I'd table this for now and just move these discussions into an issue for further discussion).

**Comment by PRoryCallahan** [comment]
@lcerrato THANKS! All of this is great.  I am so, so sorry to have made more work for you by having to add the page breaks back in. And I completely understand and agree with your priorities: get out what is not yet accessible; return to what works later.

I'm reaching the crunch part of the semester and probably will not be able to contribute much more until the summer, but I would like very much to come back and tackle what could still be done to improve these texts according to what you said.

Let me know if this sounds right for a punch list (again, not expecting you or a student to do it, I want to return to these in particular for my own work dedicated to these texts):

- [ ] Marginal MSS notation (e.g. BDEQ) moved into labels. I previously had marked the missed ones as notes as the scan had already marked the others as notes, but I did move them to where Drachmann intended the label to begin (sometimes as start of scholion, others midline at | ).
- [ ] Review block quotes
- [ ] Add the indentation notes
- [ ] Note Latin lang attributes to in-line MSS notation

I'm sure there is more, but let me know if that's a good start.

Some of Drachmann's pages are very short because there is the app. crit. but also lengthy secondary apparatus with extensive quotations from alternate sources. These pages really seemed to throw the scan off. This happened more frequently in some volumes and not in others with the initial scan. Again, I'm not sure what the machine process was, but what seemed to happen is they would break mid &lt;p&gt;, and then when it returned to the text, it would create a new &lt;div&gt;, and render the next number higher, separating text that belonged to the same part.

Again, the vast majority was extraordinarily accurate so don't take any of these as complaints!

It's fantastic for my own intended project because it saves me so much labor in reproducing Drachmann's text. In my revised edition of the scholia, I have a whole other number scheme to re-align them with the actual line numbers on which they comment (while preserving Drachmann's numbers as additional notations for cross-reference).

As for 117a. 117b. and 117, that is a typo in the original text. It should be 118. Screen Shot 2022-03-07 at 8 07 01 PM

**Comment by lcerrato** [comment]
Note: I'm working in this file presently.

**Comment by lcerrato** [comment]
@PRoryCallahan 
I should add that reviewing the Perseus Pindar should be much more quick and easy for us. With OGL I don’t know the state of a work until I dive in, but the Perseus Pindar will need only a few specific items checked.
Thank you for bringing this to our attention and doing all of this amazing work. I hope we can come out with something more useful and much improved.

**Comment by lcerrato** [comment]
Re-added print page numbers. Added third level of CTS markup to indicate part. See editorial note for guidance. Added quotes; preserved indentation; revised text where page breaks and other OCR errors resulted in missing or misplaced information; added tags and language attributes where needed including note type and language as well as lables and bibls; added xml:base to all divs.

**Comment by lcerrato** [comment]
see #2620 new PR due to Travis update

**Pull request closed without merging**
