### PR TITLE
made all files valid

### PR DESCRIPTION
**Pull request by annettegessner**
replaced Perseus publish entity as suggested by Thibault in issue #5,
replaces "argument"-tag as suggested by me in issue #5,
replaced various tags, attributes, RefsDecls etc.

All files are valid in Oxygen now except the two files containing the tag "opener" (tlg1205.tlg001.perseus-grc1 and tlg1205.tlg001.perseus-grc2) - see issue #5

### CODE REVIEW

**Comment by annettegessner** [comment]
please close #5, when done - remaining open question at #72

**Comment by annettegessner** [comment]
added div tag with n="opener" and put text inside an `<ab>`- close issue #72 when merging

**Comment by annettegessner** [comment]
@sonofmun 
Anything else to do here? Shall I move the files from the "Not_Epidoc_compliant" folder to the "Data" folder? If not, please merge and close issues #5 and #72. Thanks!

**Comment by sonofmun** [comment]
Could you move the files to the correct folders in the data/ directory? That would be great.

**Comment by annettegessner** [comment]
Done!

**Comment by sonofmun** [comment]
I will now need to go through and add \_\_cts\_\_.xml files. I will open a new issue for this.

**Comment by annettegessner** [comment]
Cool, thanks! Then I'll have a look at the files to see what needs to be done and decide when to involve Tabea and/or Peter. Can I start with the already opened issues now or shall I wait for you to do your thing?

**Comment by sonofmun** [comment]
They can already start with the open issues. Most of them will be quite easy to fix, e.g., duplicate citations or something that is not allowed.

**Pull request merged**
