### PR TITLE
Tabea issue #41

### PR DESCRIPTION
**Pull request by planatheisa**
corrected structure

### CODE REVIEW

**Comment by sonofmun** [comment]
@planatheisa Whatever you did broke Capitains compliance of the file and now it can't even be read by Capitains.

**Comment by planatheisa** [comment]
Well, I have no idea how. All I did was change the div structure, add myself in responsibility statement and change document language to greek. Also changed CTS scheme to fit the new div tags.

**Comment by sonofmun** [comment]
Don't worry about changing the responsibility statement. I will be doing a wholesale change to the TEI headers to include everyone who works on the repository.  Try taking that change out and see what happens.

**Comment by planatheisa** [comment]
I took the original file from the split file because I didn't know it was in data but I just compared both and the only difference, except those mentioned just now, was that my document still had "la" instead of "lat" for Latin.

**Comment by sonofmun** [comment]
Try again using the one from data instead. You should only be using files from the data folder for everything you are doing on this repo.

**Comment by planatheisa** [comment]
OK. I'll redo it from scratch and see what happens.

**Pull request closed without merging**
