### PR TITLE
Update tlg4016.tlg004.opp-grc2.xml

### PR DESCRIPTION
**Pull request by AlisonBabeu**
Added in author and work title
Added in language tagging
Added in file ID 
Correct bibliographic info

### CODE REVIEW

**Comment by capitains-hook** [comment]
## Global

| Changed         |   Status |
|:----------------|---------:|
| `coverage`      |    -0.07 |
| `nodes_count`   |   -27    |
| `texts_passing` |    -1    |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |   -43530 |

## Units

| Changed                                             | Status   |
|:----------------------------------------------------|:---------|
| `./data/tlg4016/tlg004/tlg4016.tlg004.opp-grc2.xml` | Failing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/1657)*

**Comment by planatheisa** [comment]
There is a `"` missing in `<teiHeader>`. Also `</ref>` is incomlete.

@AlisonBabeu

**Comment by AlisonBabeu** [comment]
I think I've made all necessary changes and this file is hopefully ready to go.

**Comment by capitains-hook** [comment]
*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/1702)*

**Comment by planatheisa** [comment]
All is well. Merging.

**Pull request merged**
