### PR TITLE
Issue 1559- Creation of new file for Olympiodorus 

### PR DESCRIPTION
**Pull request by LindaMcNulty**

### CODE REVIEW

**Comment by sonofmun** [comment]
@LindaMcNulty There are still a lot of files here that are conflicting with changes made in the master branch. I would suggest that you merge the OpenGreekandLatin master branch with your master branch and then recreate this pull request on a new branch that you create directly from your master branch.

**Comment by LindaMcNulty** [comment]
@sonofmun this is as a result of an attempted workaround I made-- for most of my past issue branches I've created since working on the tlg0057 file group, they've popped up in their old, non-passing state when I run my new pull requests in Travis (made from issues branched from my master). (They do not pop up in the local hook test.) I will do the merge that you suggest, but any ideas as to why this keeps happening?

**Comment by sonofmun** [comment]
My first guess would be because perhaps your master branch is not up to date with the OpenGreekandLatin master branch. What I would suggest is to set a "downstream" remote that you will only pull from. Try doing this in the terminal from your local First1K folder:

```
git remote set-url downstream https://github.com/OpenGreekAndLatin/First1KGreek.git
```
Then if you type the following command:

```
git remote -v
```
You should see something like:

```
origin  https://github.com/LindaMcNulty/First1KGreek.git (fetch)
origin  https://github.com/LindaMcNulty/First1KGreek.git (push)
downstream https://github.com/OpenGreekAndLatin/First1KGreek.git (fetch)
downstream  https://github.com/OpenGreekAndLatin/First1KGreek.git (push)
```
Then, change to your master branch (`git checkout master`) and type the following:

```
git pull downstream master
```
This should pull the present state of the OpenGreekandLatin master branch to your master branch. Then, when you want to push to your own copy of First1K, you would type

```
git push origin BRANCHNAME
```
So "origin" is your repo, "downstream" is OpenGreekandLatin. And don't worry about accidentally pushing something to OpenGreekandLatin. You don't have push permissions and so it will reject your push attempt.
I hope that wasn't too confusing. You can look at the documentation about doing this here: https://help.github.com/articles/changing-a-remote-s-url/

**Comment by LindaMcNulty** [comment]
Hi @sonofmun, I was able to create a downstream remote (the  `git remote set-url downstream `https://github.com/OpenGreekAndLatin/First1KGreek.git `) command didn't work but `git remote add upstream https://github.com/OpenGreekAndLatin/First1KGreek.git` did the job), but after I attempted to pull from the downstream master, I received the message that there are conflicts which need to be
resolved: 
```
From https://github.com/OpenGreekAndLatin/First1KGreek
 * branch              master     -> FETCH_HEAD
Auto-merging data/tlg0057/tlg096/tlg0057.tlg096.1st1K-grc1.xml
CONFLICT (add/add): Merge conflict in data/tlg0057/tlg096/tlg0057.tlg096.1st1K-grc1.xml
Auto-merging data/tlg0057/tlg096/__cts__.xml
CONFLICT (add/add): Merge conflict in data/tlg0057/tlg096/__cts__.xml
Auto-merging data/tlg0057/tlg095/tlg0057.tlg095.1st1K-grc1.xml
CONFLICT (content): Merge conflict in data/tlg0057/tlg095/tlg0057.tlg095.1st1K-grc1.xml
Auto-merging data/tlg0057/tlg095/__cts__.xml
CONFLICT (content): Merge conflict in data/tlg0057/tlg095/__cts__.xml
Automatic merge failed; fix conflicts and then commit the result. 
```

**Comment by sonofmun** [comment]
We can discuss resolving merge conflicts at the meeting this week.

**Comment by sonofmun** [comment]
Corrected in PR #1661

**Pull request closed without merging**
