### PR TITLE
Issue #118, tlg1205.tlg001.perseus-grc1.xml

### PR DESCRIPTION
**Pull request by jduff-chs**
Removed two extra XPath, changed pb from xml:id to n.

### CODE REVIEW

**Comment by annettegessner** [comment]
Please change in refsDecl cRefPattern n="book" to "chapter". Otherwise it looks fine.

**Comment by jduff-chs** [comment]
Ok! I am never sure what to do about that n= tag. What is their purpose?

**Comment by annettegessner** [comment]
The single lines of the refsDecl should represent the structure of the document, according to the div-tags, lines, paragraphs etc.. So your document has just one level, which means that all the div-tags are a child of div-edition and their subtype is "chapter". Thus the refsDecl should be
```xml
<cRefPattern n="chapter" matchPattern="(.+)" replacementPattern="#xpath(/tei:TEI/tei:text/tei:body/tei:div/tei:div[@n='$1'])"/>
```
Thanks for changing, merging now!

**Comment by jduff-chs** [comment]
Thanks, that is a useful explanation!

**Pull request merged**
