### PR TITLE
Added tlg2042.tlg058.1st1K-grc1.xml

### PR DESCRIPTION
**Pull request by sonofmun**
Origen Selecta in Psalmos

### CODE REVIEW

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +1 |
| `metadata_total`   |       +1 |
| `nodes_count`      |    +1622 |
| `texts_passing`    |       +1 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |  +102752 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg2042/tlg058/__cts__.xml`                   | New      |
| `./data/tlg2042/tlg058/tlg2042.tlg058.1st1K-grc1.xml` | New      |
| `./data/tlg2042/tlg058/__cts__.xml`                   | Passing  |
| `./data/tlg2042/tlg058/tlg2042.tlg058.1st1K-grc1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/3974)*

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `coverage`         |    -0.01 |
| `metadata_passing` |     1    |
| `metadata_total`   |     1    |
| `nodes_count`      |  1622    |
| `texts_passing`    |    -2    |
| `texts_total`      |     1    |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |  +102752 |

## Units

| Changed                                                   | Status   |
|:----------------------------------------------------------|:---------|
| `./data/tlg2042/tlg058/__cts__.xml`                       | New      |
| `./data/tlg2042/tlg058/tlg2042.tlg058.1st1K-grc1.xml`     | New      |
| `./data/ggm0001/ggm001/ggm0001.ggm001.1st1K-grc1.xml`     | Failing  |
| `./data/heb0001/heb010/heb0001.heb010.1st1K-eng1.xml`     | Failing  |
| `./data/stoa0033a/tlg028/stoa0033a.tlg028.1st1K-grc1.xml` | Failing  |
| `./data/tlg2042/tlg058/__cts__.xml`                       | Passing  |
| `./data/tlg2042/tlg058/tlg2042.tlg058.1st1K-grc1.xml`     | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/3977)*

**Comment by sonofmun** [comment]
Good catch. I have updated it and also put in corresp attributes since the chapter parts refer to the biblical text.

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +1 |
| `metadata_total`   |       +1 |
| `nodes_count`      |    +1623 |
| `texts_passing`    |       +1 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |  +102752 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg2042/tlg058/__cts__.xml`                   | New      |
| `./data/tlg2042/tlg058/tlg2042.tlg058.1st1K-grc1.xml` | New      |
| `./data/tlg2042/tlg058/__cts__.xml`                   | Passing  |
| `./data/tlg2042/tlg058/tlg2042.tlg058.1st1K-grc1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/4033)*

**Pull request merged**
