### PR TITLE
Added tlg1799.tlg015

### PR DESCRIPTION
**Pull request by planatheisa**

### CODE REVIEW

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +1 |
| `metadata_total`   |       +1 |
| `nodes_count`      |     +152 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |    +4713 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg1799/tlg015/__cts__.xml`                   | New      |
| `./data/tlg1799/tlg015/tlg1799.tlg015.1st1K-grc1.xml` | New      |
| `./data/tlg1799/tlg015/__cts__.xml`                   | Passing  |
| `./data/tlg1799/tlg015/tlg1799.tlg015.1st1K-grc1.xml` | Failing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/3445)*

**Comment by sonofmun** [comment]
Duplicate nodes found:
	tlg1799.tlg015.1st1K-grc1.xml	12, 12.114, 12.115, 12.116

**Comment by planatheisa** [comment]
@sonofmun 

These are actually the pages, which are not mentioned in the spreadsheet. So it's probably a different URN. Awaiting an answer on the issue in the DDD repository.

**Comment by capitains-hook** [comment]
## Global

| Changed          |   Status |
|:-----------------|---------:|
| `coverage`       |    -0.02 |
| `metadata_total` |     1    |
| `nodes_count`    |   152    |
| `texts_total`    |     1    |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |    +4713 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg5022/tlg006/__cts__.xml`                   | New      |
| `./data/tlg5022/tlg006/tlg5022.tlg006.1st1K-grc1.xml` | New      |
| `./data/tlg5022/tlg006/__cts__.xml`                   | Failing  |
| `./data/tlg5022/tlg006/tlg5022.tlg006.1st1K-grc1.xml` | Failing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/3486)*

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +1 |
| `metadata_total`   |       +1 |
| `nodes_count`      |     +152 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |    +4713 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg5022/tlg006/__cts__.xml`                   | New      |
| `./data/tlg5022/tlg006/tlg5022.tlg006.1st1K-grc1.xml` | New      |
| `./data/tlg5022/tlg006/__cts__.xml`                   | Passing  |
| `./data/tlg5022/tlg006/tlg5022.tlg006.1st1K-grc1.xml` | Failing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/3490)*

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +1 |
| `metadata_total`   |       +1 |
| `nodes_count`      |     +149 |
| `texts_passing`    |       +1 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |    +4713 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg5022/tlg006/__cts__.xml`                   | New      |
| `./data/tlg5022/tlg006/tlg5022.tlg006.1st1K-grc1.xml` | New      |
| `./data/tlg5022/tlg006/__cts__.xml`                   | Passing  |
| `./data/tlg5022/tlg006/tlg5022.tlg006.1st1K-grc1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/3498)*

**Pull request merged**
