### PR TITLE
Fixed Issue #97, tlg2313.perseus002.perseus-grc1.xml

### PR DESCRIPTION
**Pull request by jduff-chs**
Added segs around milestones, removed two extra XPath, added work-around between segs 12 and 13 across a <p> break using <lb rend=paragraph> and <p rend=continuous>, changed XPath, edited language to grc.

This was the first commit the CHS interns worked on, at the time we did not know to make a pull request.

### CODE REVIEW

**Comment by annettegessner** [comment]
Please delete the Latin in `langUsage` and you are good to go.
I would have chosen `<div type="textpart" subtype="section" n="1">` instead of `<seg n="1">`, but if I rememer what @PonteIneptique said correctly, this is fine too and the xPath is correct, so you can leave it like this.

**Comment by PonteIneptique** [comment]
@annettegessner The point here was that we could preserve `<p>` quite easily. So in these context, if people are courageous, `<seg>` is much better.

**Comment by annettegessner** [comment]
So it's better to use our div-tags, when the paragraphs end at the end of the div-tag and if we want to mark segments that end inside of a paragraph, we chose `<seg`?

**Comment by annettegessner** [comment]
Ahm ... your help in merging issues is much appreciated, @sonofmun, but @jduff-chs still has to correct the langUsage and my question has not been answered yet ...

**Comment by sonofmun** [comment]
Sorry, I missed the comment about the Latin language tag still in there. He can set up another PR to deal with that. And @PonteIneptique can still respond to the question even though the PR was merged.

**Comment by PonteIneptique** [comment]
When possible, if there is not too much crossing between passages and p (less than 10 or 5%), seg is much better because we keep nearly all the original layout.

**Comment by annettegessner** [comment]
Thanks, @PonteIneptique, I fear I might have added some closing p-tag in some files, because I didn't know how to handle this, but next time, I'll see if I can use segments.

**Comment by jduff-chs** [comment]
Hello all - thank you for the clarification @PonteIneptique, and @annettegessner and @sonofmun: I will correct the langUsage tag in another PR in a few minutes, thank you for catching it!

**Pull request merged**
