### PR TITLE
#445: corrected divs and CTS, added reference

### PR DESCRIPTION
**Pull request by planatheisa**
First upload, checking hook.

### CODE REVIEW

**Comment by planatheisa** [comment]
Still failing. "Naming conventions failed / Available in inventory failed". No idea what this means. I compared it with passing files, but I can't see what could be responsible for this. Originally the `<idno type="filename">` had a different name than the file itself but I changed that and it still doesn't pass. @sonofmun @annettegessner

**Comment by annettegessner** [comment]
"Naming conventions failed / Available in inventory failed" should have something to do with the file name being correct in the `__cts__` files. So I checked them and found a deviation:
in the `__cts__` file inside the folder of the work (tlg006)
tlg0627.tlg006.1st1K-grc1
but in the file itself, in the n-attribute of the edition-div, it's
tlg0627.tlg006.1st1K-grc2

This might cause the problem.

**Comment by planatheisa** [comment]
@annettegessner  The test is taking really long but I don't get any options to restart it when I click on details. Am I missing something?

**Comment by annettegessner** [comment]
Oh my, these are many pull requests ... I usually wait it out. If it hasn't changed by tomorrow, I will ask Thibault on the staff meeting, if he's there.

**Comment by annettegessner** [comment]
Maybe this is due to @PonteIneptique making some updates.
He suggests that people using docker hooktest should update their instance (delete and reconfigure HookTest) and read the patch change linked here:
[https://github.com/Capitains/HookTest/releases/tag/0.1.0](https://github.com/Capitains/HookTest/releases/tag/0.1.0)

**Comment by PonteIneptique** [comment]
Clicking reset once should be enough. If it does not work, its senseless to click thousand of times... I have huge maintenance to do now... : http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek

It might have been a bug, a release issue or just an http issue. But please open an issue instead of clicking this much. That's really painful for me to clean.

**Comment by PonteIneptique** [comment]
Her everyone,
Sorry I talked like that. It appears that's Annette who merged lots of PR yesterday and with the test hanging, it created bad stack of tests. I'll take care of it as soon as possible... If possible :)
Best
Thibault

**Comment by annettegessner** [comment]
Hey Thibault,
Thanks a lot for taking care of this and sorry for causing you trouble! Tabea did so much good work, I had  a lot of PRs that piled up on me, so I merged them all yesterday afternoon. I'll be more careful next time!

**Comment by PonteIneptique** [comment]
Every tests more or less are running again. I am on holidays next week and the week after, try to be gentle with homer ;)

**Comment by annettegessner** [comment]
Great!
I'll be gentle and treat poor Homer as if he was over 2000 years old! ;-)

**Comment by annettegessner** [comment]
For some reason, the hook test shown two files called "tlg0627.tlg006", but since there's only one of them in the repository, I hope it's fine. Merging.

**Pull request merged**
