### PR TITLE
#346: did a lot of stuff ages ago, also first test of tables (#251)

### PR DESCRIPTION
**Pull request by planatheisa**
Checking hook.

### CODE REVIEW

**Comment by planatheisa** [comment]
Looks good.

**Comment by sonofmun** [comment]
The @ident on the language tag should be "grc" instead of "greek". Otherwise it looks good.

**Comment by planatheisa** [comment]
Something happened to hook...

**Comment by PonteIneptique** [comment]
Test has run a second, there is duplicate node but it should be sufficient for the moment.

**Comment by sonofmun** [comment]
It looks like the file passes with the rerun test. I am merging and then I can look at the results of the new test.

**Pull request merged**
