### PR TITLE
Corrected the URN for New Testament Catenae

### PR DESCRIPTION
**Pull request by sonofmun**
…tulam Jacobi

### CODE REVIEW

**Comment by sonofmun** [comment]
@planatheisa @AlisonBabeu Take a look at the corrections here and let me know if there is anything wrong with the URNs and titles.
Also, @AlisonBabeu , do we want to have "Catenae Graecorum Patrum in Novum Testamentum" as the `<author>` for these works? Or do we want to keep it as "None"?

**Comment by AlisonBabeu** [comment]
Hi @sonofmun I think we should keep "Catenae Graecorum Patrum in Novum Testamentum" as the author or we could shorten it to "Catenae (Novum Testamentum" like the TLG uses, that way the TextGroup at least has a name and it can be helpful for grouping in the catalog.

**Comment by sonofmun** [comment]
I have updated the `<author>` elements in the `<titleStmt>` for all of these files. Take a look and see what you think, @AlisonBabeu 
Since this is a metadata change, either you can go ahead and merge it @AlisonBabeu if you have push access. If you don't have push access, then just let me know that you approve and I can merge it myself.
All the files stills pass Hook.

**Comment by AlisonBabeu** [comment]
The metadata changes for all of these look good, the only thought I have is that for the last three files it looks like you left the editor as <editor>J. A. CRAMER, S.T.P.</editor>, for consistency we might want to make the editor name all lowest case, but that is just nitpicking. I'm pretty sure I don't have push access for a pull request but I give this a thumbs up!

**Comment by planatheisa** [comment]
tlg4102.tlg001/tlg002/tlg008: no `<author>` in `biblScope` (not sure if intended)
tlg4102.tlg003/tlg004/tlg005/tlg006/tlg010: no `<author>` in `biblScope`, `<biblScope>Volume n</biblScope>` should be `<biblScope unit="volume">n</biblScope>`
tlg4102.tlg007: see above, also: `<div type"textpart" subtype="section" n="1">` has been tagged as `<div type="commentary" subtype="TOC">` in other documents.
tlg4102.tlg011: This contains only one div "chapter" which is almost 500 pages long. Looking at the scan there seems to be additional structure in something like numbered sections: [https://archive.org/stream/catenaegraecorum04cramuoft#page/162/mode/2up](url) , [https://archive.org/stream/catenaegraecorum04cramuoft#page/166/mode/2up](url) (numbers left of text). Also there are paragraphs headed with a single word ([https://archive.org/stream/catenaegraecorum04cramuoft#page/168/mode/2up](url)) which would be possible albeit probably seriously tiresome to incorporate.
tlg4102.tlg039: `<author>` in `<biblScope>` contains the editor. And `<biblScope unit="volume">` has alsways been a arabic number, here is is `vol. iii`. Probably better to change that too. Also, no link to a scan.

So much for now. More will (probably) follow.

**Comment by planatheisa** [comment]
tlg4102.tlg012/tlg013/tlg019/tlg020/tlg021/tlg022/tlg023/tlg024/tlg034/tlg035/tlg036/tlg037/tlg038: no `<author>` in `<biblScope>` (not sure if intended)
tlg4102.tlg040/tlg041/tlg043/tlg044/tlg045/tlgX01/X03:`<author>` in `<biblScope>` contains the editor. And `<biblScope unit="volume">` has alsways been a arabic number, here is is roman numbers. Also, no link to a scan.
tlg4012.tlg042: actually has `<author>` in `<biblScope>`.  `<biblScope unit="volume">` contains a roman number. Also, no scan.
tlg4102.tlgX02: <author>` in `<biblScope>` contains the editor. And `<biblScope unit="volume">` has alsways been a arabic number, here is is roman numbers. Also, no link to a scan. Also, `<div type"textpart" subtype="section" n="1">` has been tagged as `<div type="commentary" subtype="TOC">` in other documents.

The end.

**Comment by sonofmun** [comment]
I don't think we need an `<author>` element in `<biblStruct>`. The author is actually the title of the volumes, i.e., "Catenæ Græcorum Patrum in Novum Testamentum". I think we can leave it at that. What are your thoughts here, @AlisonBabeu ?

**Comment by sonofmun** [comment]
@planatheisa I think I have corrected all of the problems that you found. I think we still have some texts that have too few citation nodes (one has 157,000 words and only 24 total nodes). But take a look to see if there are any more problems that need to be fixed.

**Comment by AlisonBabeu** [comment]
Hi @sonofmun I don' think we need an additional <author> element in <biblStruct> for these files either.

**Comment by planatheisa** [comment]
Actually... I seem to have missed quite a lot:

4102/01: Still has `xml:lang="lat"` in `<listBibl>` and `"lat"` in `<langUsage>`. Also, there is a lot of text between the divs `"book" n="3"` and `"chapter" n="1"`. I think it's better to do it like 4102/02, where there we have chapter n="toc", chapter n="hypothesis" and chapter n="praef". Here we have book n="toc", book n="praef" (head: prologue), and nothing. We would then have only one cts level. Since both are similar in content it makes sense to have a similar srtucture as well.

4102/02: Same with the "lat". Also, I think `<biblScope>Volume 1</biblScope>` should be `<bibleScope unit="volume">1</biblScope>`.

4102/03: Again "lat". Here, "toc" is "commentary", where in 4102/01 and 4102/02 it is "textpart". Is there some reasoning behind this? If not, it would be better to be consistent.

So much for now. Last time I went through these a little quickly. I'll look at everything again and take some more time.

**Comment by planatheisa** [comment]
4102/04, 05, 08, 13, 19, 20, 22, 23, 24, 34, 35, 36, 37, 38: Just "lat" in `<listBibl>` and `<langUsage>`.

4102/06 and 07: Same as 4102/03.

4102/10, 12, 21: Again "lat". Here "TOC" instead of "toc" (might not matter).

4102/43: The first chapter has n="4" instead of n="hyp" (head says hypothesis).

4102/45: The first chapter is rather long. Maybe put an additional cts level like in 4102/11 ?

4102/X01: The first chapter has n="7" and I can't see why.

4102/X02: Again, the "toc" is "commentary".

Everything else is fine. That should really be all.

**Pull request merged**
