### PR TITLE
Added tlg0643.tlg001.1st1K-grc1

### PR DESCRIPTION
**Pull request by sonofmun**
Anonymus Londinensis Iatra

### CODE REVIEW

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +1 |
| `metadata_total`   |       +1 |
| `nodes_count`      |       +1 |
| `texts_passing`    |       +1 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |   +14670 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg0643/tlg001/__cts__.xml`                   | New      |
| `./data/tlg0643/tlg001/tlg0643.tlg001.1st1K-grc1.xml` | New      |
| `./data/tlg0643/tlg001/__cts__.xml`                   | Passing  |
| `./data/tlg0643/tlg001/tlg0643.tlg001.1st1K-grc1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/662)*

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +1 |
| `metadata_total`   |       +1 |
| `nodes_count`      |       +1 |
| `texts_passing`    |       +1 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |   +14670 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg0643/tlg001/__cts__.xml`                   | New      |
| `./data/tlg0643/tlg001/tlg0643.tlg001.1st1K-grc1.xml` | New      |
| `./data/tlg0643/tlg001/__cts__.xml`                   | Passing  |
| `./data/tlg0643/tlg001/tlg0643.tlg001.1st1K-grc1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/664)*

**Comment by sonofmun** [comment]
I had actually broken all of the individual poems (I think they are poems?) down into line groups but had forgotten to add those to the refsDecl. I changed the pattern a little, removing the single overarching "book" and changing the `<lg>` tags to `<div type="textpart" subtype="section>` tags. They will be easy to change if someone tells us these should be poems or songs or some such.

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +2 |
| `metadata_total`   |       +2 |
| `nodes_count`      |      +39 |
| `texts_passing`    |       +1 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |   +14670 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg0643/__cts__.xml`                          | New      |
| `./data/tlg0643/tlg001/__cts__.xml`                   | New      |
| `./data/tlg0643/tlg001/tlg0643.tlg001.1st1K-grc1.xml` | New      |
| `./data/tlg0643/__cts__.xml`                          | Passing  |
| `./data/tlg0643/tlg001/__cts__.xml`                   | Passing  |
| `./data/tlg0643/tlg001/tlg0643.tlg001.1st1K-grc1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/769)*

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +2 |
| `metadata_total`   |       +2 |
| `nodes_count`      |      +39 |
| `texts_passing`    |       +1 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |   +14670 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg0643/__cts__.xml`                          | New      |
| `./data/tlg0643/tlg001/__cts__.xml`                   | New      |
| `./data/tlg0643/tlg001/tlg0643.tlg001.1st1K-grc1.xml` | New      |
| `./data/tlg0643/__cts__.xml`                          | Passing  |
| `./data/tlg0643/tlg001/__cts__.xml`                   | Passing  |
| `./data/tlg0643/tlg001/tlg0643.tlg001.1st1K-grc1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/791)*

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `coverage`         |    -0.01 |
| `metadata_passing` |     2    |
| `metadata_total`   |     2    |
| `nodes_count`      |  1947    |
| `texts_total`      |     1    |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |   +14670 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg0643/__cts__.xml`                          | New      |
| `./data/tlg0643/tlg001/__cts__.xml`                   | New      |
| `./data/tlg0643/tlg001/tlg0643.tlg001.1st1K-grc1.xml` | New      |
| `./data/tlg0643/__cts__.xml`                          | Passing  |
| `./data/tlg0643/tlg001/__cts__.xml`                   | Passing  |
| `./data/tlg0643/tlg001/tlg0643.tlg001.1st1K-grc1.xml` | Failing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/795)*

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `coverage`         |    -0.01 |
| `metadata_passing` |     2    |
| `metadata_total`   |     2    |
| `nodes_count`      |  1947    |
| `texts_total`      |     1    |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |   +14670 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg0643/__cts__.xml`                          | New      |
| `./data/tlg0643/tlg001/__cts__.xml`                   | New      |
| `./data/tlg0643/tlg001/tlg0643.tlg001.1st1K-grc1.xml` | New      |
| `./data/tlg0643/__cts__.xml`                          | Passing  |
| `./data/tlg0643/tlg001/__cts__.xml`                   | Passing  |
| `./data/tlg0643/tlg001/tlg0643.tlg001.1st1K-grc1.xml` | Failing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/797)*

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `coverage`         |    -0.01 |
| `metadata_passing` |     2    |
| `metadata_total`   |     2    |
| `nodes_count`      |  1947    |
| `texts_total`      |     1    |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |   +14670 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg0643/__cts__.xml`                          | New      |
| `./data/tlg0643/tlg001/__cts__.xml`                   | New      |
| `./data/tlg0643/tlg001/tlg0643.tlg001.1st1K-grc1.xml` | New      |
| `./data/tlg0643/__cts__.xml`                          | Passing  |
| `./data/tlg0643/tlg001/__cts__.xml`                   | Passing  |
| `./data/tlg0643/tlg001/tlg0643.tlg001.1st1K-grc1.xml` | Failing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/804)*

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +2 |
| `metadata_total`   |       +2 |
| `nodes_count`      |    +1924 |
| `texts_passing`    |       +1 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |   +14671 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg0643/__cts__.xml`                          | New      |
| `./data/tlg0643/tlg001/__cts__.xml`                   | New      |
| `./data/tlg0643/tlg001/tlg0643.tlg001.1st1K-grc1.xml` | New      |
| `./data/tlg0643/__cts__.xml`                          | Passing  |
| `./data/tlg0643/tlg001/__cts__.xml`                   | Passing  |
| `./data/tlg0643/tlg001/tlg0643.tlg001.1st1K-grc1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/808)*

**Pull request merged**
