### PR TITLE
Tlg5026.tlg007

### PR DESCRIPTION
**Pull request by sonofmun**

### CODE REVIEW

**Comment by sonofmun** [comment]
Now passing Hook. Take a look and merge if it looks OK, @annettegessner

**Comment by sonofmun** [comment]
@PonteIneptique Didn't you say that Marianne was waiting for the Scholia in the Odyssey? If so, merge this PR and they are there!

**Comment by PonteIneptique** [comment]
I certainly hhave a look

**Comment by sonofmun** [comment]
Enclosed the first section of the epigraph in its own <div>. Still passing Hook. I have also sent instructions to DDD to correct the notes. I think that it would be OK to merge it in its present form. What do you think, @PonteIneptique ?

**Pull request merged**
