### PR TITLE
Edit/ upload tlg0594.tlg002 from DDD

### PR DESCRIPTION
**Pull request by kam5ny**

### CODE REVIEW

**Comment by lcerrato** [comment]
@AlisonBabeu 
Looks like another one from the Greek Rhetoric volume? Fairly messy, though.

**Comment by AlisonBabeu** [comment]
It is but I am happy to take care of header and metadata,etc.

**Comment by lcerrato** [comment]
@AlisonBabeu 
So... this is De figuris, I guess,  and I have no idea what the one we did yesterday is?
There is no 0087.035 accounted for in the usual places.

**Comment by AlisonBabeu** [comment]
hi @lcerrato I believe from looking at my Authors-Abbreviations-Editions spreadsheet and an earlier copy of the TLG canon ([here](https://archive.org/details/thesauruslinguae0000berk/page/166/mode/2up)), which you can see if you sign in, tlg0087.tlg035 was an older ID for this work that was renumbered 0087.056 in the current online TLG.

Screen Shot 2024-12-19 at 4 04 34 PM

**Comment by lcerrato** [comment]
> hi @lcerrato I believe from looking at my Authors-Abbreviations-Editions spreadsheet and an earlier copy of the TLG canon ([here](https://archive.org/details/thesauruslinguae0000berk/page/166/mode/2up)), which you can see if you sign in, tlg0087.tlg035 was an older ID for this work that is now tlg0087.tlg056 in the new TLG.
> 
> Screen Shot 2024-12-19 at 4 04 34 PM Screen Shot 2024-12-19 at 4 10 39 PM

One of those... ah

**Comment by lcerrato** [comment]
closed via #2826

**Pull request closed without merging**
