### PR TITLE
Issue #116

### PR DESCRIPTION
**Pull request by caitlinmiller**
Justin Martyr, Apologia II; added archive.org link, fixed XPath, fixed file name.

### CODE REVIEW

**Comment by annettegessner** [comment]
It seems maybe due to the latest merged pull requests, there are some conflicts in your branch and there are 9 changed files instead of one. Easiest way to fix this would be making a copy of the file you changed, updating your master and (new) branch and adding the changed file there and making a new pull request. Thanks!

**Comment by caitlinmiller** [comment]
@annettegessner Okay, can do, thank you!

**Comment by annettegessner** [comment]
I will close this pull request, so you can open up a "fresh one". ;-)

**Comment by annettegessner** [comment]
@caitlinmiller could you do a new pull request, please? Thanks!

**Comment by caitlinmiller** [comment]
@annettegessner  Absolutely, working on it! The same problem came up a few times so I've deleted and re-cloned the repository and will try again

**Pull request closed without merging**
