### PR TITLE
Added Galen Quos quibus (ap. Oribasius)

### PR DESCRIPTION
**Pull request by planatheisa**
Checking Hook.

### CODE REVIEW

**Comment by planatheisa** [comment]
See pull request #977.

**Comment by planatheisa** [comment]
Passing hook.

**Comment by sonofmun** [comment]
I think we need another level of citation here. The next level would be marked as `<lb n="x">`. Again, I would do this with a regex. Let me know if you have questions.

**Comment by planatheisa** [comment]
Looks good.

**Pull request merged**
