### PR TITLE
Added tlg1595.tlg221.1st1K-grc1.xml

### PR DESCRIPTION
**Pull request by sonofmun**
Philodemus De Musica Librorum Quae Exstant

### CODE REVIEW

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +2 |
| `metadata_total`   |       +2 |
| `nodes_count`      |     +150 |
| `texts_passing`    |       +1 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |   +19313 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg1595/__cts__.xml`                          | New      |
| `./data/tlg1595/tlg221/__cts__.xml`                   | New      |
| `./data/tlg1595/tlg221/tlg1595.tlg221.1st1K-grc1.xml` | New      |
| `./data/tlg1595/__cts__.xml`                          | Passing  |
| `./data/tlg1595/tlg221/__cts__.xml`                   | Passing  |
| `./data/tlg1595/tlg221/tlg1595.tlg221.1st1K-grc1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/2134)*

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +2 |
| `metadata_total`   |       +2 |
| `nodes_count`      |     +150 |
| `texts_passing`    |       +1 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |   +19313 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg1595/__cts__.xml`                          | New      |
| `./data/tlg1595/tlg221/__cts__.xml`                   | New      |
| `./data/tlg1595/tlg221/tlg1595.tlg221.1st1K-grc1.xml` | New      |
| `./data/tlg1595/__cts__.xml`                          | Passing  |
| `./data/tlg1595/tlg221/__cts__.xml`                   | Passing  |
| `./data/tlg1595/tlg221/tlg1595.tlg221.1st1K-grc1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/2136)*

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +2 |
| `metadata_total`   |       +2 |
| `nodes_count`      |     +150 |
| `texts_passing`    |       +1 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |   +19313 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg1595/__cts__.xml`                          | New      |
| `./data/tlg1595/tlg221/__cts__.xml`                   | New      |
| `./data/tlg1595/tlg221/tlg1595.tlg221.1st1K-grc1.xml` | New      |
| `./data/tlg1595/__cts__.xml`                          | Passing  |
| `./data/tlg1595/tlg221/__cts__.xml`                   | Passing  |
| `./data/tlg1595/tlg221/tlg1595.tlg221.1st1K-grc1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/2139)*

**Comment by sonofmun** [comment]
Change made.
And yes, the edition skips book 2.

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +2 |
| `metadata_total`   |       +2 |
| `nodes_count`      |     +150 |
| `texts_passing`    |       +1 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |   +19313 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg1595/__cts__.xml`                          | New      |
| `./data/tlg1595/tlg221/__cts__.xml`                   | New      |
| `./data/tlg1595/tlg221/tlg1595.tlg221.1st1K-grc1.xml` | New      |
| `./data/tlg1595/__cts__.xml`                          | Passing  |
| `./data/tlg1595/tlg221/__cts__.xml`                   | Passing  |
| `./data/tlg1595/tlg221/tlg1595.tlg221.1st1K-grc1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/2303)*

**Comment by planatheisa** [comment]
OK. Merging now.

**Pull request merged**
