### PR TITLE
Update tlg2200.tlg00447.opp-grc1.xml

### PR DESCRIPTION
**Pull request by AlisonBabeu**
Added in editor
Added in language tagging
Edited bibliographic info

### CODE REVIEW

**Comment by planatheisa** [comment]
@AlisonBabeu @sonofmun 
Does not pass, but I can't see why. Oxygen does not give me any errors. Also, see comments at #1341.

**Comment by sonofmun** [comment]
It was an error in Travis. If you click on the "Details" link next to the failed test, you see that the build actually errored. You should be able to restart the build without a problem. This happens sometimes because of hiccups in Travis.

**Comment by capitains-hook** [comment]
*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/905)*

**Comment by capitains-hook** [comment]
*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/942)*

**Comment by capitains-hook** [comment]
*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/954)*

**Pull request merged**
