### PR TITLE
ïssue #299: added quotes and changed <> to <add></add>

### PR DESCRIPTION
**Pull request by planatheisa**
Actually, there is a question open, so it's not finished yet.

### CODE REVIEW

**Comment by planatheisa** [comment]
Should be fine now.

**Comment by planatheisa** [comment]
Missed something.

**Comment by planatheisa** [comment]
Fails, no idea what's going on here.

**Comment by sonofmun** [comment]
I think your problem is here:

    Epidoc DTD validation failed
        fatal: The content of elements must consist of well-formed character data or markup. [In (L85 C2)]

Check line # 85 in the file.

**Comment by planatheisa** [comment]
Wrong document... :(

**Comment by sonofmun** [comment]
It is passing now.

**Comment by planatheisa** [comment]
At last.

**Pull request merged**
