### PR TITLE
Issue #399

### PR DESCRIPTION
**Pull request by LucieSty**
added ref url, changed lang tags, removed two levels of XPath, removed initial paragraph numbering, added vol.8 to all pb elements

### CODE REVIEW

**Comment by annettegessner** [comment]
Thanks Lucy!
Please make two small changes and we're good to go:

Change
<cRefPattern matchPattern="(\w+)" n="book" replacementPattern="#xpath(/tei:TEI/tei:text/tei:body/tei:div/tei:div[@n='$1'])"/>
to
<cRefPattern matchPattern="(\w+)" n="chapter" replacementPattern="#xpath(/tei:TEI/tei:text/tei:body/tei:div/tei:div[@n='$1'])"/>
since the citation level says "chapter" in all the div-tags

and

change
<langUsage>
        <language ident="lat">Latin</language>
        <language ident="grc">Greek</language>
      </langUsage>
to
<langUsage>
        <language ident="grc">Greek</language>
      </langUsage>
since the language used in this file is just Greek

**Comment by sonofmun** [comment]
One more procedural thing, @LucieSty , make sure when you start working on an issue to assign the issue to yourself. That way everyone else knows that you are working on it and there will be no re-duplication of effort.

**Comment by lmuellner** [comment]
Hi Matt, now that we don't have Jack working for us, who had write privileges, take only way we can do this is via a comment -- so that means you all have to _read_ the comments on an issue before you take it. Annette and I agreed to that protocol, but I'm not sure that I told Lucie about it and therefore that Lucie followed it. If not, Lucie, we have to add that step, writing a comment saying you are adopting an issue, to the guide and to the steps everyone in our group takes, at least until we decide that someone is competent enough in github and its processes to get a higher level of privileges in it. Ok? Best, Lenny

**Comment by LucieSty** [comment]
Hi All,

Yes, I saw the note, so I will be careful to write in the comments when I take on an Issue.  One problem with this issue, though, whenever Dan and I worked on it, in trying to push it up to GitHub all the corrections I did were erased.  This happened about 3 times and I notice that when Annetta sent it back, she mentioned corrections on the same issues that I had already corrected.

Should I try to fix #399 again?

Thanks,

— Lucie
Lucie Wall Stylianopoulos
Director of Academic Programs & Outreach
Art And PreModern Librarian
University of Virginia Library
Fiske Kimball Fine Arts Library
Box 400131
Charlottesville, VA 22901
Lucie@virginia.edu
434-924-6604

**Comment by sonofmun** [comment]
@LucieSty If you have the changes locally but they are not showing up in the pull request, try the following from your command line in your First1K Greek folder:

    git checkout issue-399
    git add -A
    git commit -m "Fixing the problems with tlg0627.tlg042.1st1K-grc1.xml"
    git push origin issue-399

If that pushes some changes, then it updated something and we can check it out again.  If it says that there are no changes when you try to "push", do the following steps from the command line in your First1KGreek folder:

    git checkout master
    git pull origin master
    git checkout issue-399
    git merge master

This should bring your issue-399 branch up-to-date with the master branch.
Then make your changes. Then don't forget to add and commit them:

    git add -A
    git commit -m "Fixing the problems with tlg0627.tlg042.1st1K-grc1.xml"
    git push origin issue-399

Once you do this, it should update your pull request with your latest changes.  Let me know how this works.

**Comment by sonofmun** [comment]
@LucieSty Are you still working on this branch and this pull request? If not, I will delete it and look at your new one.

**Comment by LucieSty** [comment]
Matthew,

I think we can get rid of the old branches and just use the one that too.

— Lucie
Lucie Wall Stylianopoulos
Director of Academic Programs & Outreach
Art And PreModern Librarian
University of Virginia Library
Fiske Kimball Fine Arts Library
Box 400131
Charlottesville, VA 22901
Lucie@virginia.edu
434-924-6604

**Pull request closed without merging**
