### PR TITLE
#645: corrected CTS, divs, header and langUsage

### PR DESCRIPTION
**Pull request by planatheisa**
First upload, checking hook.

### CODE REVIEW

**Comment by sonofmun** [comment]
I think this is Issue #646

**Comment by planatheisa** [comment]
yes, forgot to rename that

**Comment by planatheisa** [comment]
Not passing yet.

**Comment by sonofmun** [comment]
The URN in the XML file is incorrect. RIght now it is

    urn:cts:tlg4089.tlg004.1st1K-grc1

and it should be 
    urn:cts:greekLit:tlg4089.tlg004.1st1K-grc1

**Comment by planatheisa** [comment]
Should be fine now.

**Pull request merged**
