### PR TITLE
(tlg4034)_all_files

### PR DESCRIPTION
**Pull request by AlisonBabeu**
Updated URNs and cts_metadata.

### CODE REVIEW

**Review by lcerrato — APPROVED** [review]

**Comment by lcerrato** [comment]
@AlisonBabeu 
There are two errors here, looks like misplaced tags.

tlg4034.tlg004.1st1K-grc1.xml	 error: element "publisher" not allowed here [In (L61 C44)],  error: element "pubPlace" not allowed here [In (L62 C43)],  error: element "date" not allowed here [In (L63 C39)],  error: element "monogr" incomplete [In (L65 C34)]
[2460](https://github.com/OpenGreekAndLatin/First1KGreek/actions/runs/4690392366/jobs/8313416406#step:6:2461)
tlg4034.tlg005.1st1K-grc1.xml	 error: element "publisher" not allowed here [In (L61 C44)],  error: element "pubPlace" not allowed here [In (L62 C43)],  error: element "date" not allowed here [In (L63 C38)],  error: element "monogr" incomplete [In (L64 C34)]

**Review by lcerrato — CHANGES_REQUESTED** [review]
errors: see below

**Comment by AlisonBabeu** [comment]
hi @lcerrato. How strange, you know when I was editing the files, I got a STOA message that the schema couldn't be found. I must have messed up the tags and it didn't catch them because of that. Sorry I will go fix that!

**Comment by lcerrato** [comment]
@AlisonBabeu 
Yes, the EpiDoc site has been on and offline but it is built in to the Hooktest, so that will show the errors. I don't know why it shows a "successful" test above, but I think we should ask Jake on that. It used to be that anything less than 100% was a failure.

**Comment by AlisonBabeu** [comment]
hi @lcerrato should I open an issue in Scaife viewer for that? I won't be at the developers meeting next week!

**Comment by lcerrato** [comment]
@AlisonBabeu No, I can see the parameter for this. I may try an experiment when you are away before that.
I also think it won't do the release if it fails, so the errors may show up on the merge attempt.

Just check the hook test results as you go.

**Comment by lcerrato** [comment]
@AlisonBabeu 
Long term the stoa site is being unreliable so we may want to host the schema locally or change to 
https://epidoc.stoa.org/schema/latest/tei-epidoc.rng

As there are thousands of files this would be a massive change, so that's why I did not adopt it.

**Review by lcerrato — COMMENTED** [review]
tlg4016.tlg002.1st1K-grc1.xml 
tlg4016.tlg003.1st1K-grc1.xml 
both showing errors: available in inventory and tlg003 is showing a naming error

**Comment by lcerrato** [comment]
The errors to the tlg4016 files were in the first pull request, too. I just spotted the errors to the tlg4034 first.

**Comment by lcerrato** [comment]
In tlg4016.tlg002.1st1K-grc1.xml `<div type="edition" n="urn:cts:greekLit:tlg4016.tlg002.1st1K-grc2" xml:lang="grc">`
tlg4016.tlg004.1st1K-grc1.xml  metadata file was not updated

**Comment by AlisonBabeu** [comment]
hey @lcerrato sorry for all this. I'm going to hold off on any more changes like this until I'm back and either have a local copy of the schema to test against or if STOA proves more reliable! I will, however, fix these!

**Comment by AlisonBabeu** [comment]
hey @lcerrato so I believe my last pull request here fixed issues on tlg4034 and I opened a separate pull request to fix the ones in tlg4016.

**Review by lcerrato — APPROVED** [review]

**Pull request merged**
