### PR TITLE
Update tlg2200.tlg00437.opp-grc1.xml

### PR DESCRIPTION
**Pull request by AlisonBabeu**
Added in editor
Added in language tagging
Edited bibliographic info

### CODE REVIEW

**Comment by capitains-hook** [comment]
*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/673)*

**Comment by planatheisa** [comment]
@AlisonBabeu 
Maybe there should be an `xml:lang="deu"` in `<imprint>`? There should definitly be `xml:lang="deu"` in <langUsage>.

**Comment by AlisonBabeu** [comment]
Hi, I am not sure about ``` xml:lang="deu"``` in ```<imprint>``` because the publication city name Leipzig is not specifically German, nor is the publication year, were you thinking because of the publisher name B.G. Teubner?  What do you think @sonofmun?  I will definitely add in ```<xml:lang="deu">``` in langUsage and I missed the ```xml:lang="lat"``` on the initial title statement, thanks for catching that @planatheisa .

**Comment by capitains-hook** [comment]
*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/732)*

**Comment by sonofmun** [comment]
I think if there is no difference between a name in English and a name in German, that we don't need the `xml:lang` on that element. Both Leipzig and Teubner are the same in English and German. When it comes to a name like, e.g., Göttingen, with the umlaut over the o, then things get a bit trickier. But here I think we don't need it.

**Pull request merged**
