### PR TITLE
Update tlg2583.tlg001.1st1K-grc1.xml

### PR DESCRIPTION
**Pull request by AlisonBabeu**
Added in language tagging.
Edited bibliographic info.

### CODE REVIEW

**Comment by capitains-hook** [comment]
*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/754)*

**Comment by planatheisa** [comment]
`<langUsage>` should contain `"lat"`.

**Comment by AlisonBabeu** [comment]
I updated the language so hopefully this is all set.

**Comment by capitains-hook** [comment]
*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/844)*

**Comment by capitains-hook** [comment]
*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/858)*

**Pull request merged**
