### PR TITLE
tlg2371.001_cts_.xml and tlg2371.tlg001.opp-grc1.xml

### PR DESCRIPTION
**Pull request by AlisonBabeu**
cts_.xml file--Updated language tagging
Edited bibliographic info

tlg2371.tlg001.opp-grc1.xml
Added in language tagging
Edited bibliographic info

### CODE REVIEW

**Comment by planatheisa** [comment]
`<idno type="filename">` should be `tlg2371.tlg001.opp-grc1.xml` instead of `tlg2371.tlg001-opp-grc1.xml`.

**Comment by AlisonBabeu** [comment]
HI @planatheisa so I fixed the file ID. I think this is all set now.

**Comment by sonofmun** [comment]
@AlisonBabeu A couple more small changes: 
Could you change the `/publicationStmt/date` to 2017 instead of 2014?
Could you add `xml:lang="lat"` to `/biblStruct/series/title`?

**Comment by planatheisa** [comment]
@sonofmun One more question: Is there any specific way how we handle `<biblScope unit="volume">`? In this file we have "vol. i." and "vol. 16", in other files it only gives the volume number (like "3" or "2.3"). Maybe we should find a definite way for this. (I'd suggest arabic numbers without any "vol").

**Comment by sonofmun** [comment]
I agree with your suggestion. We should simply have an Arabic number, with decimal, comma, etc., for a multipart volume. Or, e.g, 4-6, for multiple volumes.

**Comment by AlisonBabeu** [comment]
Hi @planatheisa and @sonofmun I'm glad someone finally brought up the issue of standards with the way we encode volume numbers. I hadn't been entirely certain and I've been fairly inconsistent myself I"m afraid. I will follow what is recommended above for all future headers.

**Comment by sonofmun** [comment]
@AlisonBabeu Could you go ahead and change the two places with volume numbers that are in the header here?

**Comment by AlisonBabeu** [comment]
Hey @sonofmun I think this is all set.

**Pull request merged**
