### PR TITLE
tlg4084.tlg001-files

### PR DESCRIPTION
**Pull request by AlisonBabeu**
tlg4084_cts_.xml
Edited language tag for author name

tlg4084.001_cts_.xml
Edited language tagging
Added in bibliographic metadata

tlg4084.tlg001.opp.grc1-xml
Edited header data slightly
Added in language tagging

### CODE REVIEW

**Comment by capitains-hook** [comment]
*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/1806)*

**Comment by sonofmun** [comment]
Need to add Latin to `<langUsage>`.

**Comment by AlisonBabeu** [comment]
@sonofmun made the last change, think the file should be set.

**Comment by capitains-hook** [comment]
*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/1831)*

**Pull request merged**
