### PR TITLE
Update tlg2018.tlg011.opp-grc1.xml

### PR DESCRIPTION
**Pull request by AlisonBabeu**
Added in author.
Added in language tags.
Edited bibliographic info.

### CODE REVIEW

**Comment by sonofmun** [comment]
Hi @AlisonBabeu Hold off on making any pull requests for the text files. I have done a mass change of these files to add xml:lang attributes and we don't want to run into any unnecessary conflicts.

**Comment by AlisonBabeu** [comment]
O.k. @sonofmun, can you let me know when I can start making pull requests again. Thanks.

**Comment by sonofmun** [comment]
As soon as @PonteIneptique approves PR #1158 we can start working on the texts again. But you could do PRs with the `__cts__.xml` files right now since I didn't change any of those.

**Comment by sonofmun** [comment]
OK, @AlisonBabeu , Thibault has merged the other PR. Make sure to update your master branch before making any more changes.

**Pull request merged**
