### PR TITLE
tlg2048, tg2057, tlg2115-various file changes

### PR DESCRIPTION
**Pull request by AlisonBabeu**
I apologize @sonofmun somehow in trying to create a new branch for one set of changes I've done it all together, I will get my workflow in order next week I promise. I do think the file changes are correct though.

### CODE REVIEW

**Comment by capitains-hook** [comment]
*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/179)*

**Comment by planatheisa** [comment]
data/tlg2057/tlg002/__cts__.xml: Should be "mul" in `<ti:description>`.

data/tlg2115/tlg060/tlg2115.tlg060.opp-grc1.xml: "ger" or "deu" in `<xml:lang>`?

data/tlg2115/tlg060/tlg2115.tlg060.perseus-grc1.xml: not sure, id it's important, but if we change the publisher to the German name, maybe we should change the city/pubplace to "Göttingen" as well.

**Comment by sonofmun** [comment]
If we change the publishing place to Göttingen, then it should have an `xml:lang="deu"` attribute. If it stays as it is, it needs an `xml:lang="lat"` attribute. Either was is fine as long as we specify the language.

**Comment by capitains-hook** [comment]
## Global

| Changed         |   Status |
|:----------------|---------:|
| `coverage`      |    -0.01 |
| `texts_passing` |    -2    |

## Words

| Changed   | Status   |
|:----------|:---------|
| `UNK`     | New      |
| `grc`     | -587797  |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg2018/tlg002/tlg2018.tlg002.opp-grc3.xml`   | Failing  |
| `./data/tlg4090/tlg001/tlg4090.tlg001.1st1K-grc1.xml` | Failing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/302)*

**Comment by capitains-hook** [comment]
## Global

| Changed         |   Status |
|:----------------|---------:|
| `coverage`      |    -0.01 |
| `texts_passing` |    -2    |

## Words

| Changed   | Status   |
|:----------|:---------|
| `UNK`     | New      |
| `grc`     | -587797  |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg2018/tlg002/tlg2018.tlg002.opp-grc3.xml`   | Failing  |
| `./data/tlg4090/tlg001/tlg4090.tlg001.1st1K-grc1.xml` | Failing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/304)*

**Comment by AlisonBabeu** [comment]
@sonofmun I added in the German language attribute to the publisher tag so I think tlg215.tlg060 is all set to go.

**Comment by capitains-hook** [comment]
*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/353)*

**Comment by capitains-hook** [comment]
*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/371)*

**Pull request merged**
