### PR TITLE
Update tlg2959.tlg008.opp-grc1__cts__.xml

### PR DESCRIPTION
**Pull request by AlisonBabeu**
Edited language and added in edition info

### CODE REVIEW

**Comment by planatheisa** [comment]
To be consistent I think you should change all `xml:ang="eng"` to `"lat"`.

**Comment by sonofmun** [comment]
See discussion on #1001

**Comment by sonofmun** [comment]
@PonteIneptique This `__cts__.xml` file is not passing Hook and I am not sure why. Hook says, "0/1 file(s) with descs", which I assume refers to the `<ti:description>` element on the `<edition>`. But it is there and looks like it is formatted correctly. What am I missing?

**Comment by PonteIneptique** [comment]
You're missing xml:lang. `xml:lang` is mandatory.
Add "mul" if there is multiple language https://en.wikipedia.org/wiki/ISO_639-3#Non-language_codes

**Comment by sonofmun** [comment]
Gotcha. I will just go ahead and do this to get it passing. I am going to recreate all of these shortly in any case.

**Pull request merged**
