### PR TITLE
Update tlg2042.tlg030.opp-lat1.xml

### PR DESCRIPTION
**Pull request by AlisonBabeu**
Edited bibliographic metadata.

### CODE REVIEW

**Comment by capitains-hook** [comment]
*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/106)*

**Comment by sonofmun** [comment]
Similar question here as with PR #1227 Should this be classified as a translation or as an edition?

**Comment by capitains-hook** [comment]
*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/120)*

**Comment by capitains-hook** [comment]
*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/121)*

**Pull request merged**
