### PR TITLE
Update tlg2200.tlg00446.opp-grc1.xml

### PR DESCRIPTION
**Pull request by AlisonBabeu**
Added in editor
Added in language tagging
Edited bibliographic info

### CODE REVIEW

**Comment by capitains-hook** [comment]
*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/871)*

**Comment by planatheisa** [comment]
@AlisonBabeu 
A few things:
Is the authors name speicifically Latin? In that case it should contains `xml:lang="lat"`.
`<publicationStmt>` gives the year 2014.

**Comment by AlisonBabeu** [comment]
Hi again @planatheisa and @sonofmun. So in terms of the author's name Libanius, I haven't been encoding it as ```xml:lang="lat"``` in any of the other files, I think because I have only been encoding authors' names as Latin when there are specific separate English version of their names that are typically used, if that makes any sense. My other question is regarding the ```publicationStmt```, I had not been changing this date in any of the files as I had been going along, is that something I should start doing now? I had thought for some files published earlier in Open Greek and Latin, that the publication year would simply remain the same.

**Comment by sonofmun** [comment]
@AlisonBabeu and @planatheisa I agree that we should only put `xml:lang="lat"` for an entry that would be different in Latin than in English, e.g., Aristotle or Aristoteles (I think). As far as the publication statement, I would put 2016 or 2017 since all of these files were first published in 100% CapiTainS compliant format within the context of 1st1K. To make things easier on us, anything that is already in the repo and we are just updating, let's mark as 2016 and any new things that we add now from the stuff we have gotten back from DDD we should mark 2017. What are your thoughts here?

**Comment by planatheisa** [comment]
@sonofmun Sounds like a good idea. Maybe mention in the PR's if it's a new file, so we don't have to check every time?

**Comment by capitains-hook** [comment]
*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/939)*

**Comment by capitains-hook** [comment]
*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/950)*

**Comment by AlisonBabeu** [comment]
O.k. I can do that as well for publication dates.

**Pull request merged**
