### PR TITLE
#306: added quotes, changed <> to <add></add>

### PR DESCRIPTION
**Pull request by planatheisa**
First upload, checking hook.

### CODE REVIEW

**Comment by planatheisa** [comment]
Hook's taking an awful long time today...

**Comment by annettegessner** [comment]
Hey Tabea,
In case a hook test doesn't even start, you can abort and restart it on hook. Just clock the red "X" next to the progress-bar of the test on the overview-page of hook. Then use the link in the PR here to get a link saying "restart the test" and there you go.

**Comment by annettegessner** [comment]
Restarted text, file is passing, merging now.

**Comment by planatheisa** [comment]
Good to know, thanks.

**Pull request merged**
