### PR TITLE
Added tlg2039.tlg005.1st1K-grc1.xml

### PR DESCRIPTION
**Pull request by sonofmun**
Diaphantus Alexandrinus Fragmentum [Sp.] (e cod. Paris. gr. 2448)

### CODE REVIEW

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +2 |
| `metadata_total`   |       +2 |
| `nodes_count`      |      +93 |
| `texts_passing`    |       +1 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |    +3213 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg2039/__cts__.xml`                          | New      |
| `./data/tlg2039/tlg005/__cts__.xml`                   | New      |
| `./data/tlg2039/tlg005/tlg2039.tlg005.1st1K-grc1.xml` | New      |
| `./data/tlg2039/__cts__.xml`                          | Passing  |
| `./data/tlg2039/tlg005/__cts__.xml`                   | Passing  |
| `./data/tlg2039/tlg005/tlg2039.tlg005.1st1K-grc1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/2227)*

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +2 |
| `metadata_total`   |       +2 |
| `nodes_count`      |      +93 |
| `texts_passing`    |       +1 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |    +3213 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg2039/__cts__.xml`                          | New      |
| `./data/tlg2039/tlg005/__cts__.xml`                   | New      |
| `./data/tlg2039/tlg005/tlg2039.tlg005.1st1K-grc1.xml` | New      |
| `./data/tlg2039/__cts__.xml`                          | Passing  |
| `./data/tlg2039/tlg005/__cts__.xml`                   | Passing  |
| `./data/tlg2039/tlg005/tlg2039.tlg005.1st1K-grc1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/2236)*

**Comment by annettegessner** [comment]
The structure (refsDecl) should be only paragraphs, there are no books (or fragments - see first to fragments).
Otherwise it's looking good to me.

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +2 |
| `metadata_total`   |       +2 |
| `nodes_count`      |      +92 |
| `texts_passing`    |       +1 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |    +3213 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg2039/__cts__.xml`                          | New      |
| `./data/tlg2039/tlg005/__cts__.xml`                   | New      |
| `./data/tlg2039/tlg005/tlg2039.tlg005.1st1K-grc1.xml` | New      |
| `./data/tlg2039/__cts__.xml`                          | Passing  |
| `./data/tlg2039/tlg005/__cts__.xml`                   | Passing  |
| `./data/tlg2039/tlg005/tlg2039.tlg005.1st1K-grc1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/2253)*

**Comment by sonofmun** [comment]
refsDecl and extra level of citation fixed. Please check and merge if it looks good, @annettegessner

**Pull request merged**
