### PR TITLE
The repository should now be able to be tested with Hook

### PR DESCRIPTION
**Pull request by sonofmun**

### CODE REVIEW

**Comment by sonofmun** [comment]
@annettegessner Don't forget to delete the old branch!

**Comment by PonteIneptique** [comment]
Do not know if normal but I found a number of texts having only one citation node :')

**Comment by sonofmun** [comment]
@PonteIneptique That was the case on several of the texts. They were fragments or a block of text from someone that had no citation scheme whatsoever. I added a single node for all of these texts and we can decide later if they need something deeper or not.

**Comment by PonteIneptique** [comment]
Cool :)

**Comment by PonteIneptique** [comment]
(Note : you should add the badges to brag about it ;) )

**Comment by annettegessner** [comment]
In PL there are a number of works only having one level of citation, so this could be correct, but we'll have to check it.

**Comment by sonofmun** [comment]
@PonteIneptique I was just about to do that but was waiting for the PR to be merged.

**Pull request merged**
