### PR TITLE
Update tlg2042.tlg028.opp-grc1.xml

### PR DESCRIPTION
**Pull request by AlisonBabeu**
Added in language tagging attributes.
Added in author.
Added in file ID.
Edited bibliographic metadata.

### CODE REVIEW

**Comment by capitains-hook** [comment]
*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/97)*

**Comment by capitains-hook** [comment]
*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/99)*

**Comment by sonofmun** [comment]
This is a very interesting case. This is a text form Origen, originally in Greek, for which we have the ancient Latin translation. @PonteIneptique Should this be classified as a `<ti:translation>`? Or should it be an edition? At the very least, we need to change the file name and URN to opp-lat1 (or, better, 1st1K-lat1).

**Comment by capitains-hook** [comment]
## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |   -85625 |
| `lat`     |   +85625 |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/114)*

**Comment by PonteIneptique** [comment]
Completely agree with translation :)

**Comment by sonofmun** [comment]
Once it passes Hook, I will go ahead and merge this PR and then change the URN and the filename in another PR.

**Comment by capitains-hook** [comment]
## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |   -85625 |
| `lat`     |   +85625 |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/127)*

**Pull request merged**
