### PR TITLE
tlg4102.tlg039_tlg4102.tlg040

### PR DESCRIPTION
**Pull request by AlisonBabeu**
Per issue #1642
Renamed tlg4102.tlg039 to correct work ID of tlg4102.tlg040
Edited language tagging
Updated bibliographic metadata

@sonofmun I had changed all the files at once on my branch because the renumbering was getting confusing, but for some reasons while the cts_xml file change looks fine, Sourcetree seemed to indicate there were changes made in the xml file other than the header, which is the only thing I changed plus the bibliographic metadata. Can you do a sanity check for me and see if for some reason the file that is now supposed to be tlg4102.tlg040 is different than tlg4102.tlg039. Thanks!

### CODE REVIEW

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       -1 |
| `metadata_total`   |       -1 |
| `nodes_count`      |      -12 |
| `texts_passing`    |       -1 |
| `texts_total`      |       -1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |   -11676 |

## Units

| Changed                                             | Status   |
|:----------------------------------------------------|:---------|
| `./data/tlg4102/tlg039/__cts__.xml`                 | Deleted  |
| `./data/tlg4102/tlg039/tlg4102.tlg039.opp-grc1.xml` | Deleted  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/2712)*

**Comment by sonofmun** [comment]
@AlisonBabeu What happened here is that tlg4102.tlg040 already exists (incorrectly) as the Catena on 1 Peter. You are replacing that file with the Catenae on James and, thus, it looks like you are replacing all of the text, even though you didn't do it yourself. Basically what is being shown are the differences in the file that was tlg040 and the file that is now tlg040. It looks fine to me. 
We do need to be careful here, however. If I merge this PR, then the previous tlg4102.tlg040 (Catena on 1 Peter) will be gone. Then if you pull the master branch to your local branch, then it is gone for good unless you have renamed it already. So what I would suggest is that you go ahead and do all of the changes in this one PR, otherwise we might lose some information. I believe that was your plan at the beginning and I think it is best.

**Comment by AlisonBabeu** [comment]
Hi @sonofmun I will do that now.

**Comment by AlisonBabeu** [comment]
So something got really messed up when I stashed changes, I"m going to close this pull request but then send all my changes files in one pull request in a little bit @sonofmun .

**Pull request closed without merging**
