### PR TITLE
Renamed tlg0527.tlg030 to tlg0527.tlg034

### PR DESCRIPTION
**Pull request by sonofmun**
It is the book of Ecclesiasticus not Ecclesiastes

### CODE REVIEW

**Comment by capitains-hook** [comment]
## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg0527/tlg030/__cts__.xml`                   | Deleted  |
| `./data/tlg0527/tlg030/tlg0527.tlg030.opp-grc2.xml`   | Deleted  |
| `./data/tlg0527/tlg034/__cts__.xml`                   | New      |
| `./data/tlg0527/tlg034/tlg0527.tlg034.1st1K-grc1.xml` | New      |
| `./data/tlg0527/tlg034/__cts__.xml`                   | Passing  |
| `./data/tlg0527/tlg034/tlg0527.tlg034.1st1K-grc1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/2846)*

**Comment by AlisonBabeu** [comment]
Hi @sonofmun  I changed the title on this because at first I was confused thinking there were two tlg0527.tlg030.opp-grc2 and then I realized that there wasn't a tlg0527.tlg039, that you were instead changing the incorrect tlg0527.tlg030 to tlg0527.tlg034.

**Comment by sonofmun** [comment]
Thanks @AlisonBabeu

**Comment by capitains-hook** [comment]
## Global

| Changed         |   Status |
|:----------------|---------:|
| `nodes_count`   |    +1420 |
| `texts_passing` |       +1 |
| `texts_total`   |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |   +18710 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg0527/tlg030/__cts__.xml`                   | Deleted  |
| `./data/tlg0527/tlg030/tlg0527.tlg030.opp-grc2.xml`   | Deleted  |
| `./data/tlg0527/tlg034/__cts__.xml`                   | New      |
| `./data/tlg0527/tlg034/tlg0527.tlg034.1st1K-grc1.xml` | New      |
| `./data/tlg0527/tlg034/tlg0527.tlg034.opp-grc2.xml`   | New      |
| `./data/tlg0527/tlg034/__cts__.xml`                   | Passing  |
| `./data/tlg0527/tlg034/tlg0527.tlg034.1st1K-grc1.xml` | Passing  |
| `./data/tlg0527/tlg034/tlg0527.tlg034.opp-grc2.xml`   | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/2903)*

**Comment by capitains-hook** [comment]
## Global

| Changed         |   Status |
|:----------------|---------:|
| `nodes_count`   |    +1420 |
| `texts_passing` |       +1 |
| `texts_total`   |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |   +18710 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg0527/tlg030/__cts__.xml`                   | Deleted  |
| `./data/tlg0527/tlg030/tlg0527.tlg030.opp-grc2.xml`   | Deleted  |
| `./data/tlg0527/tlg034/__cts__.xml`                   | New      |
| `./data/tlg0527/tlg034/tlg0527.tlg034.1st1K-grc1.xml` | New      |
| `./data/tlg0527/tlg034/tlg0527.tlg034.opp-grc2.xml`   | New      |
| `./data/tlg0527/tlg034/__cts__.xml`                   | Passing  |
| `./data/tlg0527/tlg034/tlg0527.tlg034.1st1K-grc1.xml` | Passing  |
| `./data/tlg0527/tlg034/tlg0527.tlg034.opp-grc2.xml`   | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/2965)*

**Comment by planatheisa** [comment]
@sonofmun Where does this conflict come from and how do i resolve it? It seems to be with the files I just merged, but I can't see the problem.

**Comment by sonofmun** [comment]
Merge conflict fixed

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +1 |
| `metadata_total`   |       +1 |
| `nodes_count`      |    +2639 |
| `texts_passing`    |       +1 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |   +34074 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg0527/tlg030/tlg0527.tlg030.opp-grc2.xml`   | Deleted  |
| `./data/tlg0527/tlg034/__cts__.xml`                   | New      |
| `./data/tlg0527/tlg034/tlg0527.tlg034.1st1K-grc1.xml` | New      |
| `./data/tlg0527/tlg034/tlg0527.tlg034.opp-grc2.xml`   | New      |
| `./data/tlg0527/tlg034/__cts__.xml`                   | Passing  |
| `./data/tlg0527/tlg034/tlg0527.tlg034.1st1K-grc1.xml` | Passing  |
| `./data/tlg0527/tlg034/tlg0527.tlg034.opp-grc2.xml`   | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/3045)*

**Pull request merged**
