### PR TITLE
#425: corrected CTS, divs and langUsage

### PR DESCRIPTION
**Pull request by planatheisa**
First upload, checking hook.

### CODE REVIEW

**Comment by planatheisa** [comment]
Duplicates...

**Comment by planatheisa** [comment]
Looks good.

**Comment by sonofmun** [comment]
There is something strange with the citation scheme here. Hook says that it finds 5 books and 9 chapters in this work. But in the XML I only find 1 book. Can you take a look and see what is going one here, @planatheisa ? Check the XML tree to see what it might be finding instead of the `<div type="textpart" subtype="book">` as the first level of citations.

**Comment by planatheisa** [comment]
It finds the commentary-divs. Is it not supposed to?

**Comment by sonofmun** [comment]
No, it should not find the ones in commentary since that is not a part of the original text (I assume, anyway). Try changing both replacement patterns so that they have div[@type="edition"], i.e., 

    replacementPattern="#xpath(/tei:TEI/tei:text/tei:body/tei:div[@type='edition']/tei:div[@n='$1'])"

and

    replacementPattern="#xpath(/tei:TEI/tei:text/tei:body/tei:div[@type='edition']/tei:div[@n='$1']/tei:div[@n='$2'])"

**Comment by planatheisa** [comment]
Duplicates...

**Comment by planatheisa** [comment]
Do I number the commentary-divs?

**Comment by sonofmun** [comment]
Hmm, the `<div type="commentary">` elements are inside the `<div type="edition">`. I don't think this should be the case. @PonteIneptique what is your opinion here?

**Comment by PonteIneptique** [comment]
`<div type="commentary">` sibling of `<div type="edition">`. Then it could have four divs `<div type="commentary">` which are numbered

**Comment by sonofmun** [comment]
Right, so move the `<div type="commentary">` elements up so that they are siblings (instead of children) of `<div type="edition">`. Then, with @type="edition" in the replacementPattern, it should hopefully work.

**Comment by planatheisa** [comment]
Seems to be fine now.

**Comment by planatheisa** [comment]
Seems to be fine now.

**Pull request merged**
