### PR TITLE
fixed refsDecl of #108 et al.

### PR DESCRIPTION
**Pull request by annettegessner**
tlg0555.tlg001.opp-grc1.xml --> #108 
tlg0555.tlg002.opp-grc1.xml --> #109 
tlg0555.tlg005.opp-grc1.xml --> #110 
tlg0555.tlg006.opp-grc1.xml --> #111 
tlg0555.tlg007.opp-grc1.xml --> #112

### CODE REVIEW

**Comment by sonofmun** [comment]
None of these are passing. The refsDecls for all of them are general and not changed for the individual files. tlg001 and tlg002 simply have a refsDecl with too many layers. This should be an easy fix. However, the tlg005, tlg006, and tlg007 have no references found, so something more complex needs to be changed here.

**Comment by annettegessner** [comment]
Thanks, Matt!
I changed (some of) the milestones into divs, so now we have one citation level each file. I had to add quite a few `</p>` since many chapters ended mid-sentence and I couldn't / didn't want to change them all.

**Comment by annettegessner** [comment]
Very strange ... my commit doesn't show up and even my last comment here (after you, Matt) keeps popping up and disappearing, whenever I reload this page ...
The console says, everything is ok, maybe today it takes a bit longer to integrate new commits?

ebus131:First1KGreek gessner$ git checkout issue108
Already on 'issue108'
ebus131:First1KGreek gessner$ git add -A
ebus131:First1KGreek gessner$ git commit -m "correction"
[issue108 63d07ac] correction
 5 files changed, 238 insertions(+), 247 deletions(-)
ebus131:First1KGreek gessner$ git push origin issue108
Counting objects: 37, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (14/14), done.
Writing objects: 100% (14/14), 257.32 KiB | 0 bytes/s, done.
Total 14 (delta 10), reused 0 (delta 0)
To https://github.com/OpenGreekAndLatin/First1KGreek.git
   6908f9b..63d07ac  issue108 -> issue108
ebus131:First1KGreek gessner$ git status
On branch issue108
nothing to commit, working directory clean

**Comment by annettegessner** [comment]
all passing hook test now

**Comment by annettegessner** [comment]
Is hook offline now too? I checked the files locally, because I couldn't get it running online.

**Comment by sonofmun** [comment]
It is very strange on my end too. It doesn't look like Hook is registering the changes that you made. I will merge it and see what happens.

**Pull request merged**
