### PR TITLE
Added Herodianus Περὶ ὀνομάτων

### PR DESCRIPTION
**Pull request by sonofmun**
tlg0087.tlg012.1st1K-grc1.xml

### CODE REVIEW

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +2 |
| `metadata_total`   |       +2 |
| `nodes_count`      |      +29 |
| `texts_passing`    |       +1 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |    +8001 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg0087/__cts__.xml`                          | New      |
| `./data/tlg0087/tlg012/__cts__.xml`                   | New      |
| `./data/tlg0087/tlg012/tlg0087.tlg012.1st1K-grc1.xml` | New      |
| `./data/tlg0087/__cts__.xml`                          | Passing  |
| `./data/tlg0087/tlg012/__cts__.xml`                   | Passing  |
| `./data/tlg0087/tlg012/tlg0087.tlg012.1st1K-grc1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/2340)*

**Comment by planatheisa** [comment]
@sonofmun The failing test doesn't seem to concern these files. Just checking that it is save to merge.

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +3 |
| `metadata_total`   |       +3 |
| `nodes_count`      |      +33 |
| `texts_passing`    |       +3 |
| `texts_total`      |       +3 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |    +8257 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg0087/tlg012/__cts__.xml`                   | New      |
| `./data/tlg0087/tlg012/tlg0087.tlg012.1st1K-grc1.xml` | New      |
| `./data/tlg0087/tlg019/__cts__.xml`                   | New      |
| `./data/tlg0087/tlg019/tlg0087.tlg019.1st1K-grc1.xml` | New      |
| `./data/tlg0087/tlg020/__cts__.xml`                   | New      |
| `./data/tlg0087/tlg020/tlg0087.tlg020.1st1K-grc1.xml` | New      |
| `./data/tlg0087/tlg012/__cts__.xml`                   | Passing  |
| `./data/tlg0087/tlg012/tlg0087.tlg012.1st1K-grc1.xml` | Passing  |
| `./data/tlg0087/tlg019/__cts__.xml`                   | Passing  |
| `./data/tlg0087/tlg019/tlg0087.tlg019.1st1K-grc1.xml` | Passing  |
| `./data/tlg0087/tlg020/__cts__.xml`                   | Passing  |
| `./data/tlg0087/tlg020/tlg0087.tlg020.1st1K-grc1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/2381)*

**Comment by sonofmun** [comment]
Since the PR passed, that is the most important. I don't know exactly what happened on the branch itself.

**Pull request merged**
