### PR TITLE
Update tlg0018.tlg001.opp-grc1.xml

### PR DESCRIPTION
**Pull request by AlisonBabeu**
Fixed the header information including the addition of the author Philo Judaeus and an individual work title.

### CODE REVIEW

**Comment by AlisonBabeu** [comment]
My first ever pull request to First1KGreek! :)

**Comment by sonofmun** [comment]
Nicely done!

**Comment by sonofmun** [comment]
@AlisonBabeu Was there an open issue for this pull request?

**Comment by AlisonBabeu** [comment]
I had opened one  (issue)[https://github.com/OpenGreekAndLatin/First1KGreek/issues/575] for all of the Philo Judaeus headers, and had not created one for each header. Do I need to create an issue for each pull request @sonofmun?

**Pull request merged**
