### PR TITLE
Update tlg2018.tlg011__cts__.xml

### PR DESCRIPTION
**Pull request by AlisonBabeu**
Updated language tagging and edition title data.

### CODE REVIEW

**Comment by sonofmun** [comment]
Since tlg2018.tlg011.opp-lat1 is a translation of the Greek work (I assume), it should be in a ti:translation element instead of a ti:edition element.

**Comment by AlisonBabeu** [comment]
I actually don't know the answer to this question, but if this is correct, I think this means we need to go back and alter a few other cts_.xml files because I'm pretty sure this isn't our only translation.

**Comment by sonofmun** [comment]
That is true. But we are adding language detection in HookTest and so it soon should be clear where we need to go and change ti:edition to ti:translation. Don't worry about going back and looking for errors. But when you see them, go ahead and change them.

**Comment by sonofmun** [comment]
One more note here about the ti:translation element. This element requires an xml:lang attribute with the value being the language of the translation. So we need to make sure to include this when we do translations.

**Pull request merged**
