### PR TITLE
Added Lucian of Samosata Juppiter confutatus

### PR DESCRIPTION
**Pull request by sonofmun**

### CODE REVIEW

**Comment by sonofmun** [comment]
Passes Hook. Please check @planatheisa

**Comment by planatheisa** [comment]
`<title>` in `<biblStruct>` contains the author instead of the title.

**Comment by sonofmun** [comment]
The title is correct. See comment on PR #959

**Comment by planatheisa** [comment]
Here you can find the numbers in the text, though it often sticks to the preceeding word. Probably better not to have it like that.

**Pull request merged**
