### PR TITLE
Update tlg2050.tlg001.opp-grc1.xml

### PR DESCRIPTION
**Pull request by AlisonBabeu**
Added in work title and author.
Edited metadata.
Edited language tagging.

### CODE REVIEW

**Comment by capitains-hook** [comment]
*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/170)*

**Comment by capitains-hook** [comment]
*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/172)*

**Comment by planatheisa** [comment]
`xml:lang="ger"` or `xml:lang="deu"` ? @AlisonBabeu

**Comment by AlisonBabeu** [comment]
It is xml:lang="deu" I am assuming that I used the incorrect language tag?

**Comment by planatheisa** [comment]
No, in that case it's correct. I saw the other one in one of the cts files, which i unfortunately already merged.

**Comment by AlisonBabeu** [comment]
Sorry I must have slipped and put in a few incorrect ones, I'm sure we can do a global replace at some point or I will hunt them down and fix them. Thanks for all your work catching things like this! :)

**Comment by planatheisa** [comment]
Global replace sounds great. So, I will go ahead and merge all the files, where this was the only question.

**Comment by sonofmun** [comment]
As I commented on #1238 , we should replace "ger" with "deu" when we see the error. But both will be understood and so it is no big deal if the "ger" tags remain.

**Pull request merged**
