### PR TITLE
Added tlg0093.ogl001.1st1K-grc1.xml

### PR DESCRIPTION
**Pull request by sonofmun**
Theophrastus On Odours

### CODE REVIEW

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +2 |
| `metadata_total`   |       +2 |
| `nodes_count`      |      +82 |
| `texts_passing`    |       +1 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |    +5501 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg0093/__cts__.xml`                          | New      |
| `./data/tlg0093/ogl001/__cts__.xml`                   | New      |
| `./data/tlg0093/ogl001/tlg0093.ogl001.1st1K-grc1.xml` | New      |
| `./data/tlg0093/__cts__.xml`                          | Passing  |
| `./data/tlg0093/ogl001/__cts__.xml`                   | Passing  |
| `./data/tlg0093/ogl001/tlg0093.ogl001.1st1K-grc1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/2231)*

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +2 |
| `metadata_total`   |       +2 |
| `nodes_count`      |      +82 |
| `texts_passing`    |       +1 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |    +5501 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg0093/__cts__.xml`                          | New      |
| `./data/tlg0093/ogl001/__cts__.xml`                   | New      |
| `./data/tlg0093/ogl001/tlg0093.ogl001.1st1K-grc1.xml` | New      |
| `./data/tlg0093/__cts__.xml`                          | Passing  |
| `./data/tlg0093/ogl001/__cts__.xml`                   | Passing  |
| `./data/tlg0093/ogl001/tlg0093.ogl001.1st1K-grc1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/2232)*

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +2 |
| `metadata_total`   |       +2 |
| `nodes_count`      |      +82 |
| `texts_passing`    |       +1 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |    +5501 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg0093/__cts__.xml`                          | New      |
| `./data/tlg0093/ogl001/__cts__.xml`                   | New      |
| `./data/tlg0093/ogl001/tlg0093.ogl001.1st1K-grc1.xml` | New      |
| `./data/tlg0093/__cts__.xml`                          | Passing  |
| `./data/tlg0093/ogl001/__cts__.xml`                   | Passing  |
| `./data/tlg0093/ogl001/tlg0093.ogl001.1st1K-grc1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/2241)*

**Comment by AlisonBabeu** [comment]
Hi @sonofmun and @annettegessner I have one comment regarding this ID. I had cataloged this work under the Theophrastus Fragmenta ID, De Odoribus [tlg0093.tlg010x01](http://catalog.perseus.org/catalog/urn:cts:greekLit:tlg0093.tlg010x01). I'm not sure this matters but I wasn't sure if you wanted to use the same ID rather than creating a new OGL one.

**Comment by sonofmun** [comment]
Hi @AlisonBabeu My feeling here is to move away from the TLG ID on this work. They put several fragmentary works under the same ID. I would rather break them out and using an OGL ID seemed the best way. If, however, you think that it is important to maintain contact with the TLG here, then we can use that ID. Otherwise, I would perhaps add something to the catalog saying that this x01 ID refers to the same work as the ogl001 work.

**Comment by AlisonBabeu** [comment]
I am also happy to move away from the TLG ID, the extension of the fragmentary ID tlg0093.tlg010 to include all the different fragments was mostly a way of making sure all of the individual fragmentary works were aggregated together in the catalog.  I have added a note to thie work ID in the cite_collection tables until I think of a better place to put it! :)

**Pull request merged**
