### PR TITLE
tlg4102-multiple file renumbering

### PR DESCRIPTION
**Pull request by AlisonBabeu**
So @sonofmun I really hope this works.
I had to close the last pull request due to an unfortunate SourceTree incident.

This pull request should include works tlg4102.tlg040 to tlg4102.tlg045, renumber from tlg4102.tlg039 to 4102.tlg044,
with tlg4102.tlg045 to tlg4102.tlg046 having already been completed.

### CODE REVIEW

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       -1 |
| `metadata_total`   |       -1 |
| `nodes_count`      |      -20 |
| `texts_passing`    |       -1 |
| `texts_total`      |       -1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |    -4632 |

## Units

| Changed                                             | Status   |
|:----------------------------------------------------|:---------|
| `./data/tlg4102/tlg039/__cts__.xml`                 | Deleted  |
| `./data/tlg4102/tlg039/tlg4102.tlg039.opp-grc1.xml` | Deleted  |
| `./data/tlg4102/tlg045/__cts__.xml`                 | New      |
| `./data/tlg4102/tlg045/tlg4102.tlg045.opp-grc1.xml` | New      |
| `./data/tlg4102/tlg046/__cts__.xml`                 | Deleted  |
| `./data/tlg4102/tlg046/tlg4102.tlg046.opp-grc1.xml` | Deleted  |
| `./data/tlg4102/tlg045/__cts__.xml`                 | Passing  |
| `./data/tlg4102/tlg045/tlg4102.tlg045.opp-grc1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/2743)*

**Comment by sonofmun** [comment]
It looks like tlg4102.tlg046 (Catena in epistulam Juda) is being deleted here. I assume that we don't want that to happen.

**Comment by AlisonBabeu** [comment]
I don't want that to happen, I didn't put in this pull request because it
was already in the repo.

**Comment by sonofmun** [comment]
It is, however, not in your branch (https://github.com/OpenGreekAndLatin/First1KGreek/tree/tlg4102_SOS/data/tlg4102). So the repo thinks you want to delete it.

**Comment by AlisonBabeu** [comment]
Yeah I had wondered about that. I'm not in the office today so I will add that file back into my repo and submit the pull request again tomorrow.

**Comment by AlisonBabeu** [comment]
I added in those files back, hope that means we can clean this infernal pull request @sonofmun

**Comment by capitains-hook** [comment]
## Units

| Changed                                             | Status   |
|:----------------------------------------------------|:---------|
| `./data/tlg4102/tlg039/__cts__.xml`                 | Deleted  |
| `./data/tlg4102/tlg039/tlg4102.tlg039.opp-grc1.xml` | Deleted  |
| `./data/tlg4102/tlg045/__cts__.xml`                 | New      |
| `./data/tlg4102/tlg045/tlg4102.tlg045.opp-grc1.xml` | New      |
| `./data/tlg4102/tlg045/__cts__.xml`                 | Passing  |
| `./data/tlg4102/tlg045/tlg4102.tlg045.opp-grc1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/2758)*

**Comment by capitains-hook** [comment]
## Units

| Changed                                             | Status   |
|:----------------------------------------------------|:---------|
| `./data/tlg4102/tlg039/__cts__.xml`                 | Deleted  |
| `./data/tlg4102/tlg039/tlg4102.tlg039.opp-grc1.xml` | Deleted  |
| `./data/tlg4102/tlg045/__cts__.xml`                 | New      |
| `./data/tlg4102/tlg045/tlg4102.tlg045.opp-grc1.xml` | New      |
| `./data/tlg4102/tlg045/__cts__.xml`                 | Passing  |
| `./data/tlg4102/tlg045/tlg4102.tlg045.opp-grc1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/2787)*

**Comment by capitains-hook** [comment]
## Units

| Changed                                             | Status   |
|:----------------------------------------------------|:---------|
| `./data/tlg4102/tlg039/__cts__.xml`                 | Deleted  |
| `./data/tlg4102/tlg039/tlg4102.tlg039.opp-grc1.xml` | Deleted  |
| `./data/tlg4102/tlg045/__cts__.xml`                 | New      |
| `./data/tlg4102/tlg045/tlg4102.tlg045.opp-grc1.xml` | New      |
| `./data/tlg4102/tlg045/__cts__.xml`                 | Passing  |
| `./data/tlg4102/tlg045/tlg4102.tlg045.opp-grc1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/2788)*

**Pull request merged**
