### PR TITLE
Added tlg0643.opp001.1st1K-lat1.xml

### PR DESCRIPTION
**Pull request by sonofmun**
Preface to Anonymi Londinensis ex Aristotelis iatricis Menoniis et aliis medicis eclogae

### CODE REVIEW

**Comment by sonofmun** [comment]
@annettegessner and @planatheisa , I would like both of you to take a look at this when you can. This is a new "commentary" type and I am both interested to have you see the format and to get your feedback. Make sure to look at the `__cts__.xml` files as well, especially the one at the work level.

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +2 |
| `metadata_total`   |       +2 |
| `nodes_count`      |      +38 |
| `texts_passing`    |       +1 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `lat`     |    +4104 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg0643/__cts__.xml`                          | New      |
| `./data/tlg0643/opp001/__cts__.xml`                   | New      |
| `./data/tlg0643/opp001/tlg0643.opp001.1st1K-lat1.xml` | New      |
| `./data/tlg0643/__cts__.xml`                          | Passing  |
| `./data/tlg0643/opp001/__cts__.xml`                   | Passing  |
| `./data/tlg0643/opp001/tlg0643.opp001.1st1K-lat1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/568)*

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +2 |
| `metadata_total`   |       +2 |
| `nodes_count`      |      +38 |
| `texts_passing`    |       +1 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `lat`     |    +4104 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg0643/__cts__.xml`                          | New      |
| `./data/tlg0643/opp001/__cts__.xml`                   | New      |
| `./data/tlg0643/opp001/tlg0643.opp001.1st1K-lat1.xml` | New      |
| `./data/tlg0643/__cts__.xml`                          | Passing  |
| `./data/tlg0643/opp001/__cts__.xml`                   | Passing  |
| `./data/tlg0643/opp001/tlg0643.opp001.1st1K-lat1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/669)*

**Comment by planatheisa** [comment]
@sonofmun 
The text part of it looks fine to me. I guess we're not dealing with footnotes at the moment? There are some symbols, greek letters with diacritica probably, which show up as boxes. Not sure if that only happens for me or not. In the header I noticed, that the xml declaration differs from what we have in the other documents. Also it would be useful to add the scan here too.
Other than that, looking good. Is there any other commentary type text in the book (like tocs or indices or whatever)? Would they be all in one document or would there be several?

**Comment by planatheisa** [comment]
One more question: Why does is say `xml:lang="grc"` in `<ti:work>` ?

**Comment by sonofmun** [comment]
@planatheisa Thanks for taking such a careful look. 
We are not yet dealing with footnotes, etc. 
All of the Greek letters look fine for me in the browser. It does appear that some of them were actually recognized as Arabic letters.
I need to update the XML header. I simply forgot to do that. And I will add the scan.
The way I am going about it is that I am splitting out every part into its own XML file. So TOC is one file, Introduction is another file, etc. The idea is always one work, one file. And I see all of these as different works. What are your thoughts on this? Also, some of the matter is about the whole volume, some only about a single work.
And you are right, the xml:lang for this work should be lat.

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +2 |
| `metadata_total`   |       +2 |
| `nodes_count`      |      +38 |
| `texts_passing`    |       +1 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `lat`     |    +4104 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg0643/__cts__.xml`                          | New      |
| `./data/tlg0643/opp001/__cts__.xml`                   | New      |
| `./data/tlg0643/opp001/tlg0643.opp001.1st1K-lat1.xml` | New      |
| `./data/tlg0643/__cts__.xml`                          | Passing  |
| `./data/tlg0643/opp001/__cts__.xml`                   | Passing  |
| `./data/tlg0643/opp001/tlg0643.opp001.1st1K-lat1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/763)*

**Comment by planatheisa** [comment]
@sonofmun @annettegessner 

Looking good now. Should I merge it or wait for Annette's opinion?

**Comment by sonofmun** [comment]
@planatheisa Go ahead and merge it. Where I asked for reviews from both you and @annettegessner , I just wanted either one of you to review it, not necessarily both.

**Pull request merged**
