### PR TITLE
Update header and other info tlg2959.tlg003.opp-ger1.xml

### PR DESCRIPTION
**Pull request by AlisonBabeu**
Updated header and bilbiographic info. Also added in German as language tag since this work is in German.

### CODE REVIEW

**Comment by sonofmun** [comment]
A couple more things to change. First, since @xml:lang="grc" and @xml:lang="lat" do not existing in this document, we should delete those lines in `<langUsage>` as well. Also, the @xml:lang="lat" attribute needs to be deleted from the `<editor>/<persName>/<name>` element. And, finally, since the work is in german, could you add an @xml:lang="de" attribute to the `<div type="edition">` element?

**Comment by sonofmun** [comment]
Also, I just noticed that you define the @xml:lang attribute for German as "de", but then you use "ger" in the elements. I think you should change @xml:lang="ger" to @xml:lang="de".

**Comment by AlisonBabeu** [comment]
Yeah I noticed that halfway through, I think it is that in the MODS records I create I have gotten used to using the language tags they use for Marc records which is still ger for German rather than de for Deutsch. I'll go through the files and change all of this for consistency.

**Comment by sonofmun** [comment]
@AlisonBabeu According to @PonteIneptique, we should use the three letter language codes from ISO 693-3. That means instead of 'de', we should use 'deu'. And following up on the metadata conversation from yesterday, could you add an `@xml:lang="lat"` attribute to `<titleStmt>/<title>`?

**Pull request merged**
