### PR TITLE
Added tlg9010.tlg001

### PR DESCRIPTION
**Pull request by planatheisa**
Checking Hook. I wasn't entirely sure how to do this lexicon.

### CODE REVIEW

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +2 |
| `metadata_total`   |       +2 |
| `nodes_count`      |   +13306 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |  +274623 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg9010/__cts__.xml`                          | New      |
| `./data/tlg9010/tlg001/__cts__.xml`                   | New      |
| `./data/tlg9010/tlg001/tlg9010.tlg001.1st1K-grc1.xml` | New      |
| `./data/tlg9010/__cts__.xml`                          | Passing  |
| `./data/tlg9010/tlg001/__cts__.xml`                   | Passing  |
| `./data/tlg9010/tlg001/tlg9010.tlg001.1st1K-grc1.xml` | Failing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/3772)*

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +2 |
| `metadata_total`   |       +2 |
| `nodes_count`      |   +13302 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |  +274623 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg9010/__cts__.xml`                          | New      |
| `./data/tlg9010/tlg001/__cts__.xml`                   | New      |
| `./data/tlg9010/tlg001/tlg9010.tlg001.1st1K-grc1.xml` | New      |
| `./data/tlg9010/__cts__.xml`                          | Passing  |
| `./data/tlg9010/tlg001/__cts__.xml`                   | Passing  |
| `./data/tlg9010/tlg001/tlg9010.tlg001.1st1K-grc1.xml` | Failing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/3773)*

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +2 |
| `metadata_total`   |       +2 |
| `nodes_count`      |   +13302 |
| `texts_passing`    |       +1 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |  +274623 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg9010/__cts__.xml`                          | New      |
| `./data/tlg9010/tlg001/__cts__.xml`                   | New      |
| `./data/tlg9010/tlg001/tlg9010.tlg001.1st1K-grc1.xml` | New      |
| `./data/tlg9010/__cts__.xml`                          | Passing  |
| `./data/tlg9010/tlg001/__cts__.xml`                   | Passing  |
| `./data/tlg9010/tlg001/tlg9010.tlg001.1st1K-grc1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/3775)*

**Comment by sonofmun** [comment]
I like the way you set this up. We also have the other two volumes of the lexicon, don't we? If so, you should add those two volumes to this file so that the whole lexicon shows up as a single work and a single file.

**Comment by planatheisa** [comment]
Is there a way to tie the publication date to the volume number other than just order of listing?
@sonofmun

**Comment by sonofmun** [comment]
The typical, bibliographical way of doing this would be simply to put a date range for the publication date, e.g., "1886-1905" or something.  You can also have more than one `<monogr>` element. Since the definition for the `<monogr>` element is "contains bibliographic elements describing an item (e.g. a book or journal) published as an independent item (i.e. as a separate physical object).", and since each volume is a "separate physical object", I would describe each of the volumes with its own `<monogr>` element.

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +1 |
| `metadata_total`   |       +1 |
| `nodes_count`      |   +23898 |
| `texts_passing`    |       -1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |  +491162 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg0559/tlg016/__cts__.xml`                   | Deleted  |
| `./data/tlg0559/tlg016/tlg0559.tlg016.1st1K-grc1.xml` | Deleted  |
| `./data/tlg9010/__cts__.xml`                          | New      |
| `./data/tlg9010/tlg001/__cts__.xml`                   | New      |
| `./data/tlg9010/tlg001/tlg9010.tlg001.1st1K-grc1.xml` | New      |
| `./data/tlg9010/__cts__.xml`                          | Passing  |
| `./data/tlg9010/tlg001/__cts__.xml`                   | Passing  |
| `./data/tlg9010/tlg001/tlg9010.tlg001.1st1K-grc1.xml` | Failing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/3825)*

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +3 |
| `metadata_total`   |       +3 |
| `nodes_count`      |   +24244 |
| `texts_passing`    |       +1 |
| `texts_total`      |       +2 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |  +500273 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg0559/tlg014/__cts__.xml`                   | New      |
| `./data/tlg0559/tlg014/tlg0559.tlg014.1st1K-grc1.xml` | New      |
| `./data/tlg9010/__cts__.xml`                          | New      |
| `./data/tlg9010/tlg001/__cts__.xml`                   | New      |
| `./data/tlg9010/tlg001/tlg9010.tlg001.1st1K-grc1.xml` | New      |
| `./data/tlg0559/tlg014/__cts__.xml`                   | Passing  |
| `./data/tlg0559/tlg014/tlg0559.tlg014.1st1K-grc1.xml` | Passing  |
| `./data/tlg9010/__cts__.xml`                          | Passing  |
| `./data/tlg9010/tlg001/__cts__.xml`                   | Passing  |
| `./data/tlg9010/tlg001/tlg9010.tlg001.1st1K-grc1.xml` | Failing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/3830)*

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +3 |
| `metadata_total`   |       +3 |
| `nodes_count`      |   +24244 |
| `texts_passing`    |       +1 |
| `texts_total`      |       +2 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |  +500273 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg0559/tlg014/__cts__.xml`                   | New      |
| `./data/tlg0559/tlg014/tlg0559.tlg014.1st1K-grc1.xml` | New      |
| `./data/tlg9010/__cts__.xml`                          | New      |
| `./data/tlg9010/tlg001/__cts__.xml`                   | New      |
| `./data/tlg9010/tlg001/tlg9010.tlg001.1st1K-grc1.xml` | New      |
| `./data/tlg0559/tlg014/__cts__.xml`                   | Passing  |
| `./data/tlg0559/tlg014/tlg0559.tlg014.1st1K-grc1.xml` | Passing  |
| `./data/tlg9010/__cts__.xml`                          | Passing  |
| `./data/tlg9010/tlg001/__cts__.xml`                   | Passing  |
| `./data/tlg9010/tlg001/tlg9010.tlg001.1st1K-grc1.xml` | Failing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/3832)*

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +3 |
| `metadata_total`   |       +3 |
| `nodes_count`      |   +24244 |
| `texts_passing`    |       +2 |
| `texts_total`      |       +2 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |  +500273 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg0559/tlg014/__cts__.xml`                   | New      |
| `./data/tlg0559/tlg014/tlg0559.tlg014.1st1K-grc1.xml` | New      |
| `./data/tlg9010/__cts__.xml`                          | New      |
| `./data/tlg9010/tlg001/__cts__.xml`                   | New      |
| `./data/tlg9010/tlg001/tlg9010.tlg001.1st1K-grc1.xml` | New      |
| `./data/tlg0559/tlg014/__cts__.xml`                   | Passing  |
| `./data/tlg0559/tlg014/tlg0559.tlg014.1st1K-grc1.xml` | Passing  |
| `./data/tlg9010/__cts__.xml`                          | Passing  |
| `./data/tlg9010/tlg001/__cts__.xml`                   | Passing  |
| `./data/tlg9010/tlg001/tlg9010.tlg001.1st1K-grc1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/3834)*

**Pull request merged**
