### PR TITLE
Added Lucian of Samosata Revivescentes sive piscator

### PR DESCRIPTION
**Pull request by sonofmun**

### CODE REVIEW

**Comment by sonofmun** [comment]
Passes Hook. Please check @planatheisa

**Comment by planatheisa** [comment]
`<title>` in `<biblStruct>` contains the author instead of the title. Also, there are footnotes but no indication which part of the text they're referring to. Not sure, if something should be done about that.

**Comment by sonofmun** [comment]
The title is correct. See comment on PR #959
Was this the only work where the footnotes were not marked in the text?

**Comment by sonofmun** [comment]
Looking at the texts we got back from DDD, it looks like they didn't mark the location of the notes. I am going to check and if there are not that many, I will simply do it myself and push the changes.

**Comment by planatheisa** [comment]
OK. So I merge only those without footnotes for now?

**Comment by planatheisa** [comment]
I looked it over again, and actually often you can find the numbers for the footnotes in the text if you look at the whole page, but in many cases they stick to the preceeding word, which should probably amended.

**Comment by sonofmun** [comment]
@planatheisa This is something that we are going to need to correct by hand, I think. Basically, the way these footnotes would need to be encoded to make them usable by Nemo is for the text of the footnote to be moved to the appropriate place in the text and then encoded as `<note n="X" place="foot">`, as in the following example:

```
<pb n="2"/>
<head><note place="foot">MSS. available in photographs: Γ, UPΝ.</note>
ΑΝΑΒΙΟΥΝΤΕΣ Η ΑΛΙΕΥΣ<note n="1" place="foot">1 ΑΝΑΒΙΟΥΝΤΕΣ Η ΑΛΙΕΥΣ γ (and Thomas Magister):
ΑΛΙΕΥΣ Η ΑΝΑΒΙΟΥΝΤΕΣ β</note></head>
<div type="textpart" subtype="section" n="1">
<sp>
<speaker>ΣΩΚΡΑΤΗΣ</speaker>
<p>1 Βάλλε βάλλε τὸν κατάρατον ἀφθόνοις τοῖς λίθοις·
ἐπίβαλλε τῶν βώλων· προσεπίβαλλε καὶ
τῶν ὀστράκων· παῖε τοῖς ξύλοις τὸν ἀλιτήριον·
ὅρα μὴ διαφύγῃ· καὶ σὺ βάλλε, ὦ Πλάτων· καὶ
σύ, ὦ Χρύσιππε, καὶ σὺ δέ, καὶ πάντες ἅμα·<note n="2" place="foot">2 Punctuation A M.H.: καὶ σὺ δὲ καὶ πάντες ἅμα συν. γ ; καὶ
σὺ δέ, πάντες ἅμα συν. β, edd.</note>
συνασπίσωμεν ἐπʼ αὐτόν,
<lg>
<l>ὡς πήρη πήρῃφιν ἀρήγῃ, βάκτρα δὲ βάκτροις,</l>
</lg>
κοινὸς γὰρ πολέμιος, καὶ οὐκ ἔστιν ἡμῶν ὅντινα
οὐχ ὕβρικε. σὺ δέ, ὦ Διόγενες, εἴ ποτε καὶ
ἄλλοτε, χρῶ τῷ ξύλῳ· μηδὲ ἀνῆτε· διδότω τὴν
ἀξίαν βλάσφημος ὤν. τί τοῦτο; κεκμήκατε, ὦ
Ἐπίκουρε καὶ Ἀρίστιππε; καὶ μὴν οὐκ ἐχρῆν.
<lg>
<l>ἀνέρες ἔστε, σοφοί, μνήσασθε δὲ θούριδος ὀργῆς.</l>
</lg></p>
</sp>
</div>

<div type="textpart" subtype="section" n="2">
<p>2 Ἀριστότελες, ἐπισπούδασον· ἔτι θᾶττον. <note n="3" place="foot">3 Punctuation Κ. Schwartz: ἐπισπούδασον ἔτι θᾶττον MSS.</note> εὖ
ἔχει· ἑάλωκεν τὸ θηρίον. εἰλήφαμέν σε, ὦ μιαρέ.
εἴσῃ γοῦν αὐτίκα οὕστινας ἡμᾶς ὄντας ἐκακηγόρεῖς.
```

How do you feel about doing these types of corrections?

**Comment by sonofmun** [comment]
Otherwise, the text of the notes will show up at some random place or not at all.

**Comment by planatheisa** [comment]
Greta had the idea of replacing the footnote marker with the footnote tag, and have it moved when it is displayed.

**Comment by sonofmun** [comment]
Do you have an example of how you would code that?

**Comment by planatheisa** [comment]
Something like that:
` <div type="textpart" subtype="section" n="5">
                    <p>5 Ἢ γὰρ οὐ ταῦτα σεμνολογοῦσιν οἱ ποιηταὶ περὶ τῶν θεῶν καὶ πολὺ τούτων
                        ἱερώτερα περί τε Ἡφαίστου καὶ Προμηθέως καὶ Κρόνου καὶ Ῥέας καὶ σχεδὸν ὅλης
                        τῆς τοῦ Διὸς οἰκίας; καὶ ταῦτα παρακαλέσαντες τὰς Μούσας συνῳδοὺς ἐν ἀρχῇ
                        τῶν ἐπῶν, ὑφʼ ὧν δὴ ἔνθεοι γενόμενοι, ὡς τὸ εἰκός, ᾄδουσιν ὡς ὁ μὲν Κρόνος
                        ἐπειδὴ τάχιστα ἐξέτεμε τὸν πατέρα τὸν Οὐρανόν, ἐβασίλευσέν τε ἐν αὐτῷ καὶ τὰ
                        τέκνα κατήσθιεν ὥσπερ ὁ Ἀργεῖος Θυέστης ὕστερον· ὁ δὲ Ζεὺς 1 κλαπεὶς ὑπὸ τῆς
                        Ῥέας ὑποβαλομένης τὸν λίθον εἰς τὴν Κρήτην ἐκτεθεὶς ὑπʼ αἰγὸς ἀνετράφη
                        καθάπερ ὁ Τήλεφος <note type="footnote">1 Θυέστης· ὕστερον δὲ ὁ Ζεὺς
                            γ.</note>
                        <pb n="160"/> ὑπὸ ἐλάφου καὶ ὁ Πέρσης Κῦρος ὁ πρότερος ὑπὸ τῆς κυνός, εἶτ᾿ 
                        ἐξελάσας τὸν πατέρα καὶ εἰς τὸ δεσμωτήριον καταβαλὼν αὐτὸς ἔσχε τὴν ἀρχήν·
                        ἔγημε δὲ πολλὰς μὲν καὶ ἄλλας, ὑστάτην δὲ τὴν ἀδελφὴν <note type="footnote">1 τὴς Ἥραν τὴν ἀδελφὴν β.</note> κατὰ τοὺς Περσῶν καὶ
                        <note type="footnote">2 τοῦτο καὶ β.</note> Ἀσσυρίων νόμους· ἐρωτικὸς δὲ ὢν καὶ εἰς τὰ ἀφροδίσια ἐκκεχυμένος <note type="footnote">3 ἐκκεχυμένος Cobet: κεχυμένος, MSS.</note> ῥᾳδίως
                        ἐνέπλησε παίδων τὸν οὐρανόν, τοὺς μὲν ἐξ ὁμοτίμων ποιησάμενος, ἐνίους δὲ
                        νόθους ἐκ τοῦ θνητοῦ καὶ ἐπιγείου γένος, ἄρτι μὲν ὁ γεννάδας γενόμενος
                        χρυσός, ἄρτι δὲ ταῦρος ἢ κύκνος ἢ ἀετός, καὶ ὅλως ποικιλώτερος αὐτοῦ
                        Πρωτέως· μόνην δὲ τὴν Ἀθηνᾶν ἔφυσεν ἐκ τῆς ἑαυτοῦ κεφαλῆς ὑπʼ αὐτὸν ἀτεχνῶς
                        τὸν ἐγκέφαλον συλλαβών· τὸν μὲν γὰρ Διόνυσον ἡμιτελῆ, φασίν, ἐκ τῆς μητρὸς
                        ἔτι καιομένης ἁρπάσας ἐν τῷ μηρῷ φέρων κατώρυξε κἆτα ἐξέτεμεν τῆς ὠδῖνος
                        ἐνστάσης.</p>
                </div>

                <div type="textpart" subtype="section" n="6">
                    <p>6 Ὅμοια δὲ τούτοις καὶ περὶ τῆς Ἥρας ᾄδουσιν, ἄνευ τῆς πρὸς τὸν ἄνδρα ὁμιλίας
                        ὑπηνέμιον αὐτὴν παῖδα γεννῆσαι τὸν Ἥφαιστον, οὐ μάλα εὐτυχῆ τοῦτον, ἀλλὰ
                        βάναυσον καὶ χαλκέα καὶ πυρίτην, ἐν καπνῷ τὸ πᾶν βιοῦντα καὶ σπινθήρων
                        ἀνάπλεων οἷα δὴ καμινευτήν, καὶ οὐδὲ ἄρτιον τὼ πόδε· χωλευθῆναι γὰρ αὐτὸν
                        ἀπὸ τοῦ πτώματος, ὁπότε ἐρρίφη ὑπὸ τοῦ Διὸς ἐξ οὐρανοῦ, καὶ εἴ γε μὴ οἱ
                        Λήμνιοι καλῶς ποιοῦντες ἔτι φερόμενον αὐτὸν ὑπεδέξαντο, κἂν ἐτεθνήκει ἡμῖν ὁ
                        Ἥφαιστος ὥσπερ ὁ Ἀστυάναξ ἀπὸ τοῦ πύργου καταπεσών.</p> `

**Comment by sonofmun** [comment]
Looking at the original file, I find 180 footnotes, but only about 100 numbers marked in the text that would seem to indicate that footnotes exist on the page.

**Comment by planatheisa** [comment]
No, sorry. That didn't work at all.

**Comment by sonofmun** [comment]
If you want to put a block of XML in, the best way is to leave one blank line, then have a line that only has \`\`\`, then to put your code block, and then end it on a new line with, again, only \`\`\`. Give that a try.

**Comment by planatheisa** [comment]
`<pb n="160"/> ὑπὸ ἐλάφου καὶ ὁ Πέρσης Κῦρος ὁ πρότερος ὑπὸ τῆς κυνός, εἶτ᾿ 
ἐξελάσας τὸν πατέρα καὶ εἰς τὸ δεσμωτήριον καταβαλὼν αὐτὸς ἔσχε τὴν ἀρχήν·
ἔγημε δὲ πολλὰς μὲν καὶ ἄλλας, ὑστάτην δὲ τὴν ἀδελφὴν <note type="footnote"
>1 τὴς Ἥραν τὴν ἀδελφὴν β.</note> κατὰ τοὺς Περσῶν καὶ <note
type="footnote">2 τοῦτο καὶ β.</note> Ἀσσυρίων νόμους· ἐρωτικὸς δὲ ὢν
καὶ εἰς τὰ ἀφροδίσια ἐκκεχυμένος <note type="footnote">3 ἐκκεχυμένος Cobet:
κεχυμένος, MSS.</note> ῥᾳδίως ἐνέπλησε παίδων τὸν οὐρανόν, τοὺς μὲν ἐξ
ὁμοτίμων ποιησάμενος, ἐνίους δὲ νόθους ἐκ τοῦ θνητοῦ καὶ ἐπιγείου γένος,
ἄρτι μὲν ὁ γεννάδας γενόμενος χρυσός, ἄρτι δὲ ταῦρος ἢ κύκνος ἢ ἀετός, καὶ
oλως ποικιλώτερος αὐτοῦ Πρωτέως· μόνην δὲ τὴν Ἀθηνᾶν ἔφυσεν ἐκ τῆς ἑαυτοῦ
κεφαλῆς ὑπʼ αὐτὸν ἀτεχνῶς τὸν ἐγκέφαλον συλλαβών· τὸν μὲν γὰρ Διόνυσον
ἡμιτελῆ, φασίν, ἐκ τῆς μητρὸς ἔτι καιομένης ἁρπάσας ἐν τῷ μηρῷ φέρων
κατώρυξε κἆτα ἐξέτεμεν τῆς ὠδῖνος ἐνστάσης.</p>
</div>

<div type="textpart" subtype="section" n="6">
<p>6 Ὅμοια δὲ τούτοις καὶ περὶ τῆς Ἥρας ᾄδουσιν, ἄνευ τῆς πρὸς τὸν ἄνδρα ὁμιλίας
 ὑπηνέμιον αὐτὴν παῖδα γεννῆσαι τὸν Ἥφαιστον, οὐ μάλα εὐτυχῆ τοῦτον, ἀλλὰ
 βάναυσον καὶ χαλκέα καὶ πυρίτην, ἐν καπνῷ τὸ πᾶν βιοῦντα καὶ σπινθήρων
 ἀνάπλεων οἷα δὴ καμινευτήν, καὶ οὐδὲ ἄρτιον τὼ πόδε· χωλευθῆναι γὰρ αὐτὸν
 ἀπὸ τοῦ πτώματος, ὁπότε ἐρρίφη ὑπὸ τοῦ Διὸς ἐξ οὐρανοῦ, καὶ εἴ γε μὴ οἱ
 Λήμνιοι καλῶς ποιοῦντες ἔτι φερόμενον αὐτὸν ὑπεδέξαντο, κἂν ἐτεθνήκει ἡμῖν ὁ
Hαιστος ὥσπερ ὁ Ἀστυάναξ ἀπὸ τοῦ πύργου καταπεσών.</p>
<pb n="162"/>`

**Comment by planatheisa** [comment]
This formatting drives me nuts. I hope you can understand what I mean...

**Comment by planatheisa** [comment]
```````````````````````````````````````````````````````````````````
<pb n="160"/>
ὑπὸ ἐλάφου καὶ ὁ Πέρσης Κῦρος ὁ πρότερος ὑπὸ
τῆς κυνός, εἶτ᾿  ἐξελάσας τὸν πατέρα καὶ εἰς τὸ
δεσμωτήριον καταβαλὼν αὐτὸς ἔσχε τὴν ἀρχήν·
ἔγημε δὲ πολλὰς μὲν καὶ ἄλλας, ὑστάτην δὲ
τὴν ἀδελφὴν <note type="footnote">1 τὴς Ἥραν τὴν ἀδελφὴν β.
</note> κατὰ τοὺς Περσῶν καὶ <note type="footnote">2 τοῦτο καὶ β.
</note> Ἀσσυρίων
νόμους· ἐρωτικὸς δὲ ὢν καὶ εἰς τὰ ἀφροδίσια ἐκκεχυμένος
<note type="footnote">3 ἐκκεχυμένος Cobet: κεχυμένος, MSS.</note>
ῥᾳδίως ἐνέπλησε παίδων τὸν οὐρανόν,
τοὺς μὲν ἐξ ὁμοτίμων ποιησάμενος, ἐνίους δὲ
νόθους ἐκ τοῦ θνητοῦ καὶ ἐπιγείου γένος, ἄρτι
μὲν ὁ γεννάδας γενόμενος χρυσός, ἄρτι δὲ ταῦρος
ἢ κύκνος ἢ ἀετός, καὶ ὅλως ποικιλώτερος αὐτοῦ
Πρωτέως· μόνην δὲ τὴν Ἀθηνᾶν ἔφυσεν ἐκ τῆς
ἑαυτοῦ κεφαλῆς ὑπʼ αὐτὸν ἀτεχνῶς τὸν ἐγκέφαλον
συλλαβών· τὸν μὲν γὰρ Διόνυσον ἡμιτελῆ,
φασίν, ἐκ τῆς μητρὸς ἔτι καιομένης ἁρπάσας ἐν
τῷ μηρῷ φέρων κατώρυξε κἆτα ἐξέτεμεν τῆς
ὠδῖνος ἐνστάσης.</p>
</div>

<div type="textpart"  subtype="section"  n="6">
<p>6 Ὅμοια δὲ τούτοις καὶ περὶ τῆς Ἥρας ᾄδουσιν,
ἄνευ τῆς πρὸς τὸν ἄνδρα ὁμιλίας ὑπηνέμιον αὐτὴν
παῖδα γεννῆσαι τὸν Ἥφαιστον, οὐ μάλα εὐτυχῆ
τοῦτον, ἀλλὰ βάναυσον καὶ χαλκέα καὶ πυρίτην,
ἐν καπνῷ τὸ πᾶν βιοῦντα καὶ σπινθήρων ἀνάπλεων
οἷα δὴ καμινευτήν, καὶ οὐδὲ ἄρτιον τὼ πόδε·
χωλευθῆναι γὰρ αὐτὸν ἀπὸ τοῦ πτώματος, ὁπότε
ἐρρίφη ὑπὸ τοῦ Διὸς ἐξ οὐρανοῦ, καὶ εἴ γε μὴ οἱ
Λήμνιοι καλῶς ποιοῦντες ἔτι φερόμενον αὐτὸν
ὑπεδέξαντο, κἂν ἐτεθνήκει ἡμῖν ὁ Ἥφαιστος
ὥσπερ ὁ Ἀστυάναξ ἀπὸ τοῦ πύργου
καταπεσών.</p>
````````````````````````````````````````````````````

**Comment by planatheisa** [comment]
Much better. Thanks.

**Comment by sonofmun** [comment]
I think I understand. So leave it as `<note type="footnote">` and just move it up into the text.
So the question is: is this something that we want to do ourselves for these texts? Or should I send them back to DDD for correction? There are 180 footnotes in the whole first volume and 118 in the second volume. That includes all of the Lucian texts in these 16 pull requests.

**Comment by planatheisa** [comment]
Hm. If it only concerns this volume, we could probably do it ourselves. Question is, what about all the other stuff by DDD? I haven't checked all the footnotes. At one point it did become too much work and Simona didn't want to spend too much time on them. I just happend to notice myself.

**Comment by planatheisa** [comment]
I think the idea was, at long as it could be done at some point in the future, not to worry about it now. But if we can't find where the footnotes go, it is a much bigger concern.

**Comment by sonofmun** [comment]
I agree that we do not want to do it for all of the stuff that we have gotten back up to this point. I think what we want to do in the future is to try to get DDD to do it for us. I think they should be able to handle it.
Do you want to check these PRs, merge them if there are no other problems? Then we can put issues in for these files. Maybe we can get the fellows at UVA to work on this with us.

**Comment by planatheisa** [comment]
OK. Should I check if all footnotes correspond somewhere or leave that too?

**Comment by sonofmun** [comment]
Using a better regex, I think I can actually find all of the places where footnotes need to be added in this file. So the only bit of work may be matching them up. Let me try it here and see how long it takes with this file. Don't merge anything yet.

**Comment by planatheisa** [comment]
The treatment of footnotes is in general a big mess whith many different approaches over the last years which it will take some work to have some consistency there.

**Comment by sonofmun** [comment]
OK, so I think I got all of the footnotes. It took the most time to write the regex to be able to do it. Check it out.
And before you merge anything else, let me go through and mark in the other files where the footnotes belong on the page. That will make the whole process a lot easier.

**Comment by planatheisa** [comment]
So, I can merge them then and leave the moving of the footnotes to someone else (or just for another day)?

**Comment by sonofmun** [comment]
Once I push again to one of the PRs with the message that I have inserted the placeholders for the footnotes, you can merge those PRs. I am about half way through right now.

**Comment by sonofmun** [comment]
And I have done this text already.

**Comment by planatheisa** [comment]
Check.

**Pull request merged**
