### PR TITLE
Added tlg0643.tlg001.1st1K-lat1^Cml

### PR DESCRIPTION
**Pull request by sonofmun**
Signorum Explicatio to Anonymus Londinensis Iatrica

### CODE REVIEW

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +2 |
| `metadata_total`   |       +2 |
| `nodes_count`      |      +17 |
| `texts_passing`    |       +1 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `lat`     |     +109 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg0643/__cts__.xml`                          | New      |
| `./data/tlg0643/tlg001/__cts__.xml`                   | New      |
| `./data/tlg0643/tlg001/tlg0643.tlg001.1st1K-lat1.xml` | New      |
| `./data/tlg0643/__cts__.xml`                          | Passing  |
| `./data/tlg0643/tlg001/__cts__.xml`                   | Passing  |
| `./data/tlg0643/tlg001/tlg0643.tlg001.1st1K-lat1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/659)*

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +2 |
| `metadata_total`   |       +2 |
| `nodes_count`      |      +17 |
| `texts_passing`    |       +1 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `lat`     |     +109 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg0643/__cts__.xml`                          | New      |
| `./data/tlg0643/tlg001/__cts__.xml`                   | New      |
| `./data/tlg0643/tlg001/tlg0643.tlg001.1st1K-lat1.xml` | New      |
| `./data/tlg0643/__cts__.xml`                          | Passing  |
| `./data/tlg0643/tlg001/__cts__.xml`                   | Passing  |
| `./data/tlg0643/tlg001/tlg0643.tlg001.1st1K-lat1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/667)*

**Comment by sonofmun** [comment]
I will add the scan.
The `xml:lang="grc"` is actually correct here. This is a commentary that is referring directly to a single work, so I have added it to the `__cts__.xml` file for that work. The work is in Greek, and so the xml:lang for the whole work is grc. The other two commentaries were commentaries on a volume of multiple works, so I gave them their own work-level URN since they don't fall neatly under a single ancient work.
The opp in the URN is there because that is the project in which we produced the URN and because those works are not described anywhere by TLG identifiers. Here, though, we have a TLG identifier for the Iatrica and so we use that. The only semantics in that part of the identifier is the project where the identifier was produced. It doesn't say anything about the work or edition itself.

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +2 |
| `metadata_total`   |       +2 |
| `nodes_count`      |      +17 |
| `texts_passing`    |       +1 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `lat`     |     +109 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg0643/__cts__.xml`                          | New      |
| `./data/tlg0643/tlg001/__cts__.xml`                   | New      |
| `./data/tlg0643/tlg001/tlg0643.tlg001.1st1K-lat1.xml` | New      |
| `./data/tlg0643/__cts__.xml`                          | Passing  |
| `./data/tlg0643/tlg001/__cts__.xml`                   | Passing  |
| `./data/tlg0643/tlg001/tlg0643.tlg001.1st1K-lat1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/767)*

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +2 |
| `metadata_total`   |       +2 |
| `nodes_count`      |      +17 |
| `texts_passing`    |       +1 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `lat`     |     +109 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg0643/__cts__.xml`                          | New      |
| `./data/tlg0643/tlg001/__cts__.xml`                   | New      |
| `./data/tlg0643/tlg001/tlg0643.tlg001.1st1K-lat1.xml` | New      |
| `./data/tlg0643/__cts__.xml`                          | Passing  |
| `./data/tlg0643/tlg001/__cts__.xml`                   | Passing  |
| `./data/tlg0643/tlg001/tlg0643.tlg001.1st1K-lat1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/792)*

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +2 |
| `metadata_total`   |       +2 |
| `nodes_count`      |      +17 |
| `texts_passing`    |       +1 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `lat`     |     +109 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg0643/__cts__.xml`                          | New      |
| `./data/tlg0643/tlg001/__cts__.xml`                   | New      |
| `./data/tlg0643/tlg001/tlg0643.tlg001.1st1K-lat1.xml` | New      |
| `./data/tlg0643/__cts__.xml`                          | Passing  |
| `./data/tlg0643/tlg001/__cts__.xml`                   | Passing  |
| `./data/tlg0643/tlg001/tlg0643.tlg001.1st1K-lat1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/796)*

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +2 |
| `metadata_total`   |       +2 |
| `nodes_count`      |      +17 |
| `texts_passing`    |       +1 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `lat`     |     +109 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg0643/__cts__.xml`                          | New      |
| `./data/tlg0643/tlg001/__cts__.xml`                   | New      |
| `./data/tlg0643/tlg001/tlg0643.tlg001.1st1K-lat1.xml` | New      |
| `./data/tlg0643/__cts__.xml`                          | Passing  |
| `./data/tlg0643/tlg001/__cts__.xml`                   | Passing  |
| `./data/tlg0643/tlg001/tlg0643.tlg001.1st1K-lat1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/801)*

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +2 |
| `metadata_total`   |       +2 |
| `nodes_count`      |      +17 |
| `texts_passing`    |       +1 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `lat`     |     +109 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg0643/__cts__.xml`                          | New      |
| `./data/tlg0643/tlg001/__cts__.xml`                   | New      |
| `./data/tlg0643/tlg001/tlg0643.tlg001.1st1K-lat1.xml` | New      |
| `./data/tlg0643/__cts__.xml`                          | Passing  |
| `./data/tlg0643/tlg001/__cts__.xml`                   | Passing  |
| `./data/tlg0643/tlg001/tlg0643.tlg001.1st1K-lat1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/802)*

**Pull request merged**
