### PR TITLE
Update tlg0358.tlg001.1st1K-grc1.xml

### PR DESCRIPTION
**Pull request by AlisonBabeu**
updated the header with some language tagging.

### CODE REVIEW

**Comment by capitains-hook** [comment]
## Global

| Changed         |   Status |
|:----------------|---------:|
| `coverage`      |    -0.09 |
| `nodes_count`   | -3954    |
| `texts_passing` |    -3    |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |   -15985 |
| `mul`     |   -18265 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg0643/tlg001/tlg0643.tlg001.1st1K-mul1.xml` | Failing  |
| `./data/tlg0643/tlg001/tlg0643.tlg001.1st1K-mul2.xml` | Failing  |
| `./data/tlg2022/tlg003/tlg2022.tlg003.opp-grc1.xml`   | Failing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/1602)*

**Comment by capitains-hook** [comment]
*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/1630)*

**Comment by planatheisa** [comment]
I'd merge this but I'm not sure why it does not pass everything. It does not seem to have to do with this file though. @sonofmun

**Comment by sonofmun** [comment]
This was a problem with three files from the master branch that started failing after we added another test to HookTest. I have corrected those files and merged them into the master branch. So notice that the PR test on Travis passes. That means that once this is merged into the master branch, it will pass all the tests. The failing files are on Alison's branch, not the master branch.
Does that make sense?

**Comment by planatheisa** [comment]
Yes, thanks. I have never been sure about these tests and what information to get from them. So /push need not concern me? Maybe unless it's my own PR?

**Comment by sonofmun** [comment]
The PR test is more important because it should represent what the repository will look like if the PR is merged. That being said, if one passes and one fails, you should always look for the reason why. Most of the time it is actually because one of the tests crashed on Travis and just needs to be restarted. But sometimes it is something more nefarious, like it is here.

**Comment by planatheisa** [comment]
Ok, thanks. Then I will merge this now.

**Pull request merged**
