### PR TITLE
Added tlg0363.tlg001.1st1K-grc1.xml

### PR DESCRIPTION
**Pull request by sonofmun**
Claudius Ptolemaeus Syntaxis mathematica
This file needs a LOT of attention because of the tables, diagrams, the missing content on pages because the layout was landscape instead of portrait, etc.

### CODE REVIEW

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +1 |
| `metadata_total`   |       +1 |
| `nodes_count`      |     +171 |
| `texts_passing`    |       +1 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |  +178076 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg0363/tlg001/__cts__.xml`                   | New      |
| `./data/tlg0363/tlg001/tlg0363.tlg001.1st1K-grc1.xml` | New      |
| `./data/tlg0363/tlg001/__cts__.xml`                   | Passing  |
| `./data/tlg0363/tlg001/tlg0363.tlg001.1st1K-grc1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/1245)*

**Comment by sonofmun** [comment]
@annettegessner Issue #1408 is there to remind us to correct this text after we get it in the repository. I wouldn't try to fix it before we add it, though. It would take too long and require too much effort. I think we should add it now and get it fixed later.

**Comment by annettegessner** [comment]
Suggestions for @sonofmun :
- To show, that there is some figure or table missing in the text, and enable somebody to put further work into it, if he or she wants to improve the text, I think it's necessary to annotate these missing figures and tables and preferably add a link to a reference PDF - see [issue 251](https://github.com/OpenGreekAndLatin/First1KGreek/issues/251).
For this file I am using for figure e.g.
<figure><graphic url="https://archive.org/stream/claudiiptolemae00ptolgoog#page/n92/mode/1up"/></figure>
and for table e.g.
<figure rend="table"><graphic url="https://archive.org/stream/claudiiptolemae00ptolgoog#page/n91/mode/1up"/></figure>
Let me know, if you think this makes sense to you for now or if we should discuss this further in issue 251!


Notes to self:
- using "list" instead of "figure" for annotating tables was not valid
- we don't have the time to add those very long missing tables manually, so I suggested linking to the PDF as with figures
--> maybe don't even bother with giving the URL or anything and just indicate, there is something missing here to save time?
- there are a lot of Greek letters with an overline, indicating a line segment (if I am not mistaken), but I don't think there is anything we can (and want to) do about this
- since some of the PDF at Hathi Trust are restricted, I used alternative PDFs for [Vol. 1](https://archive.org/details/claudiiptolemae00ptolgoog) and [Vol. 2](https://archive.org/details/claudiiptolemae07ptolgoog)
- got to [page 333}(https://archive.org/stream/claudiiptolemae00ptolgoog#page/n346/mode/1up) and did not add and commit yet

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +1 |
| `metadata_total`   |       +1 |
| `nodes_count`      |     +171 |
| `texts_passing`    |       +1 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |  +178075 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg0363/tlg001/__cts__.xml`                   | New      |
| `./data/tlg0363/tlg001/tlg0363.tlg001.1st1K-grc1.xml` | New      |
| `./data/tlg0363/tlg001/__cts__.xml`                   | Passing  |
| `./data/tlg0363/tlg001/tlg0363.tlg001.1st1K-grc1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/1590)*

**Pull request merged**
