### PR TITLE
Edited .travis.yml to work with HookTest 0.2.2

### PR DESCRIPTION
**Pull request by sonofmun**

### CODE REVIEW

**Comment by sonofmun** [comment]
This works now. If you could take a look, @PonteIneptique , to make sure that everything looks good with the .travis.yml file, that would be great.

**Comment by sonofmun** [comment]
Wait. One more quick change.

**Comment by sonofmun** [comment]
Now take a look!

**Comment by PonteIneptique** [comment]
I think you should take the chance to write the Readme badges at the same time :)

**Comment by sonofmun** [comment]
Will do.

**Comment by PonteIneptique** [comment]
https://raw.githubusercontent.com/OpenGreekAndLatin/csel-dev/master/README.md

**Comment by PonteIneptique** [comment]
Just thing about changing "lat" to "grc" for the language badge :D

**Comment by sonofmun** [comment]
I have added the badges with all of the different languages. They don't show up correctly in the preview so I  hope it looks OK in the live version.

**Pull request merged**
