### PR TITLE
tlg4089.tlg003-file changes

### PR DESCRIPTION
**Pull request by AlisonBabeu**
tlg4089.tlg003_cts_.xml
Edited language tagging
Added in bibliographic details

tlg4089.tlg003.opp-grc1.xml
Edited language tagging
Edited bibliographic data
Added series data

tlg4089.tlg003.1st1K-grc1.xml
Edited language tagging
Edited bibliographic data
Added series data

### CODE REVIEW

**Comment by capitains-hook** [comment]
*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/1813)*

**Comment by sonofmun** [comment]
Need to add Latin to `<langUsage>` in tlg4089.tlg003.1st1K-grc1.xml

**Comment by AlisonBabeu** [comment]
Added in Latin language tag, so @sonofmun I think the file should be all set.

**Comment by capitains-hook** [comment]
*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/1832)*

**Pull request merged**
