### PR TITLE
Added tlg0732.tlg012 (Alexander of Aphrodisias Quaestiones)

### PR DESCRIPTION
**Pull request by sonofmun**
from http://www.graeco-arabic-studies.org/
Also added .gitignore

### CODE REVIEW

**Comment by sonofmun** [comment]
The text and its metadata file pass Hook.

**Comment by sonofmun** [comment]
@annettegessner Could you merge this? I would like to show it during the OGL meeting today.

**Comment by sonofmun** [comment]
Or perhaps @PonteIneptique could merge this?

**Comment by PonteIneptique** [comment]
You should add more information, like where you got it form, and how it was transcribed if you can. Probably add this in the TEI

**Comment by sonofmun** [comment]
Should I put the URL in sourceDesc? Maybe in a `<bibl>` element?

**Comment by sonofmun** [comment]
`<publicationStatement>` would have also made sense. I did it differently (under `<sourceDesc>`)

**Comment by sonofmun** [comment]
Still passing Hook.

**Pull request merged**
