### PR TITLE
Added tlg0643.opp002.1st1K-lat1.xml

### PR DESCRIPTION
**Pull request by sonofmun**
Epimetrum to Anonymi Londinensis ex Aristotelis iatricis Menoniis et aliis medicis eclogae

### CODE REVIEW

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +2 |
| `metadata_total`   |       +2 |
| `nodes_count`      |       +1 |
| `texts_passing`    |       +1 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `lat`     |     +281 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg0643/__cts__.xml`                          | New      |
| `./data/tlg0643/opp002/__cts__.xml`                   | New      |
| `./data/tlg0643/opp002/tlg0643.opp002.1st1K-lat1.xml` | New      |
| `./data/tlg0643/__cts__.xml`                          | Passing  |
| `./data/tlg0643/opp002/__cts__.xml`                   | Passing  |
| `./data/tlg0643/opp002/tlg0643.opp002.1st1K-lat1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/657)*

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +2 |
| `metadata_total`   |       +2 |
| `nodes_count`      |       +1 |
| `texts_passing`    |       +1 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `lat`     |     +281 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg0643/__cts__.xml`                          | New      |
| `./data/tlg0643/opp002/__cts__.xml`                   | New      |
| `./data/tlg0643/opp002/tlg0643.opp002.1st1K-lat1.xml` | New      |
| `./data/tlg0643/__cts__.xml`                          | Passing  |
| `./data/tlg0643/opp002/__cts__.xml`                   | Passing  |
| `./data/tlg0643/opp002/tlg0643.opp002.1st1K-lat1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/663)*

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +2 |
| `metadata_total`   |       +2 |
| `nodes_count`      |       +1 |
| `texts_passing`    |       +1 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `lat`     |     +281 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg0643/__cts__.xml`                          | New      |
| `./data/tlg0643/opp002/__cts__.xml`                   | New      |
| `./data/tlg0643/opp002/tlg0643.opp002.1st1K-lat1.xml` | New      |
| `./data/tlg0643/__cts__.xml`                          | Passing  |
| `./data/tlg0643/opp002/__cts__.xml`                   | Passing  |
| `./data/tlg0643/opp002/tlg0643.opp002.1st1K-lat1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/765)*

**Comment by sonofmun** [comment]
Since you approved @planatheisa, I will merge.

**Pull request merged**
