### PR TITLE
#215 split translation

### PR DESCRIPTION
**Pull request by annettegessner**
splitted Latin translation from Greek text manually, since it was only 9 pages and the div tags were better than in other files

### CODE REVIEW

**Comment by sonofmun** [comment]
/tlg2768/tlg002/tlg2768.tlg002.opp-lat1.xml needs to be added to the `__cts__.xml` file.

**Comment by annettegessner** [comment]
forgot to change the __cts__ file.
Both files passing hook test now.

**Comment by sonofmun** [comment]
Just add the following lines to `__cts__.xml` as a direct child of `<ti:work>`

    <ti:edition urn="urn:cts:greekLit:tlg2768.tlg002.opp-lat1" workUrn="urn:cts:greekLit:tlg2768.tlg002">
        <ti:label xml:lang="eng">According to Eusebius and Theognius</ti:label>
        <ti:description xml:lang="eng">Gelasius, According to Eusebius and Theognius</ti:description
    </ti:edition>

**Comment by annettegessner** [comment]
geeeeez, I already figured all on my own and I made it "latinLit" instead of "greekLit"
:-P

**Comment by sonofmun** [comment]
The Latin translation should still be in the greekLit domain, not in the latinLit domain. You need to change that back.

**Comment by annettegessner** [comment]
done - passing hook test

**Pull request merged**
