### PR TITLE
Update tlg2042.tlg045.1st1K-grc1.xml

### PR DESCRIPTION
**Pull request by AlisonBabeu**
Added in author and editor info.
Edited bibliographic info.
Added in series statement

### CODE REVIEW

**Comment by capitains-hook** [comment]
*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/156)*

**Comment by planatheisa** [comment]
There are two editors in `<teiHeader>` but only one in `<biblStruct>` ? I this meant to be? @AlisonBabeu

**Comment by AlisonBabeu** [comment]
Nope, there should be two editors here. I'll fix that.

**Comment by capitains-hook** [comment]
## Global

| Changed         |   Status |
|:----------------|---------:|
| `coverage`      |    -0.01 |
| `texts_passing` |    -2    |

## Words

| Changed   | Status   |
|:----------|:---------|
| `UNK`     | New      |
| `grc`     | -587797  |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg2018/tlg002/tlg2018.tlg002.opp-grc3.xml`   | Failing  |
| `./data/tlg4090/tlg001/tlg4090.tlg001.1st1K-grc1.xml` | Failing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/300)*

**Comment by capitains-hook** [comment]
*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/367)*

**Pull request merged**
