### PR TITLE
Added tlg1595.tlg370

### PR DESCRIPTION
**Pull request by planatheisa**
First upload. Checking.

### CODE REVIEW

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +2 |
| `metadata_total`   |       +2 |
| `nodes_count`      |       +2 |
| `texts_passing`    |       +1 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |    +9798 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg1595/__cts__.xml`                          | New      |
| `./data/tlg1595/tlg370/__cts__.xml`                   | New      |
| `./data/tlg1595/tlg370/tlg1595.tlg370.1st1K-grc1.xml` | New      |
| `./data/tlg1595/__cts__.xml`                          | Passing  |
| `./data/tlg1595/tlg370/__cts__.xml`                   | Passing  |
| `./data/tlg1595/tlg370/tlg1595.tlg370.1st1K-grc1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/1712)*

**Comment by annettegessner** [comment]
@planatheisa Hi Tabea,
CTS-file and header look all very good to me. Only thing I am not sure about is the structure and length of the file. It seems the proposed ref target link is to another edition, so it doesn't match up, but the file going up to page 62 seems too short.
Please let me know, if you'd like to make some changes or if we should add an issue for this file. After that, I'll gladly merge the file.

**Comment by planatheisa** [comment]
@annettegessner 

This is all the DDD-file consisted of and there is not other work in the spreadsheet that fits, although the word count does not match up at all. I'm not sure how to proceed in this case.

**Comment by sonofmun** [comment]
For some reason we got only a very small portion of this work back from DDD. We need to check what happened here. For now, I would simply close this PR and wait until we get a fuller version.

**Comment by planatheisa** [comment]
OK

**Pull request closed without merging**
