### PR TITLE
Update tlg2200.tlg00442.opp-grc1.xml

### PR DESCRIPTION
**Pull request by AlisonBabeu**
Added in editor
Added in language tagging
Edited bibliographic info

### CODE REVIEW

**Comment by capitains-hook** [comment]
*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/693)*

**Comment by planatheisa** [comment]
Why are there two pull requests for tlg2200.tlg0442.opp-grc1.xml (#1311 and #1313)?

**Comment by AlisonBabeu** [comment]
I think there are two because I made a mistake!  Whoops. I'll close one! Thanks for catching that!

**Comment by capitains-hook** [comment]
## Global

| Changed         |   Status |
|:----------------|---------:|
| `coverage`      |    -0.07 |
| `nodes_count`   |   -31    |
| `texts_passing` |    -1    |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |    -4715 |

## Units

| Changed                                                 | Status   |
|:--------------------------------------------------------|:---------|
| `./data/tlg2200/tlg00442/tlg2200.tlg00442.opp-grc1.xml` | Failing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/743)*

**Comment by sonofmun** [comment]
There is something wrong with tlg2200.tlg00442.opp-grc1.xml. None of the tests are passing and this is usually because the file can't be parsed. Check it in Oxygen to see if there is a tag that isn't closed or a tag that is not allowed somewhere.

**Comment by AlisonBabeu** [comment]
So @sonofmun I opened this file in Oxygen and it checked out as completely valid

**Comment by sonofmun** [comment]
@AlisonBabeu The problem was that you had forgotten the `lang` part of the `xml:lang` attribute in the `<title>` element. Therefore the text could not parse. I am surprised that your Oxygen didn't show this error. Mine did. I have gone ahead and corrected it.

**Comment by capitains-hook** [comment]
*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/852)*

**Comment by capitains-hook** [comment]
*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/855)*

**Comment by AlisonBabeu** [comment]
I'm surprised it didn't show it either, huh. Thanks for catching the error.

**Pull request merged**
