### PR TITLE
Corrected stoa0146d.stoa001

### PR DESCRIPTION
**Pull request by sonofmun**
Separated the Greek from the Latin

Inserted chapter divisions from the scanned edition

Corrected teiHeader

### CODE REVIEW

**Comment by sonofmun** [comment]
Passes Hook. Please check @planatheisa or @annettegessner

**Comment by PonteIneptique** [comment]
Was hast du mit dem Deutschen Text gemacht ?

**Comment by sonofmun** [comment]
What do you mean?

**Comment by PonteIneptique** [comment]
The whole intro has been removed it seems ?

**Comment by sonofmun** [comment]
I removed anything that is not the text itself. That includes front and back matter.

**Comment by sonofmun** [comment]
Perhaps I shouldn't have? I was still thinking in terms of CSEL where we have all of the original volumes also in the repo. Here we don't have that.

**Comment by PonteIneptique** [comment]
I really think it's time we have a ti:commentary item for front...

**Comment by PonteIneptique** [comment]
Let me think about this one. I might implement ti:commentary. It won't be CTS compliant but will be DTS compliant.

**Comment by sonofmun** [comment]
That would be a good solution, I think. After all, if we say one file, one text, then we shouldn't be including the introduction to an edition with the edition itself. They are two different texts.

**Comment by PonteIneptique** [comment]
I'll merge that but could you open an issue on CapiTainS.github.io repository ?

**Comment by sonofmun** [comment]
On the github.io repository?

**Comment by PonteIneptique** [comment]
https://github.com/Capitains/capitains.github.io/

**Comment by sonofmun** [comment]
Got it. Will do.

**Pull request merged**
