### PR TITLE
Changed tlg2001.tlg043.opp-grc1.xml to opp-lat1.xml

### PR DESCRIPTION
**Pull request by sonofmun**
Also corrected metadata
Replaced PR #1503 and #1618

### CODE REVIEW

**Comment by capitains-hook** [comment]
## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |   -87346 |
| `lat`     |   +87346 |

## Units

| Changed                                             | Status   |
|:----------------------------------------------------|:---------|
| `./data/tlg2001/tlg043/tlg2001.tlg043.opp-grc1.xml` | Deleted  |
| `./data/tlg2001/tlg043/tlg2001.tlg043.opp-lat1.xml` | New      |
| `./data/tlg2001/tlg043/tlg2001.tlg043.opp-lat1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/2293)*

**Comment by sonofmun** [comment]
It looks like the only other level we could have here would be for the paragraphs. I will add those.

**Comment by capitains-hook** [comment]
## Global

| Changed       |   Status |
|:--------------|---------:|
| `nodes_count` |     +411 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |   -87346 |
| `lat`     |   +87346 |

## Units

| Changed                                             | Status   |
|:----------------------------------------------------|:---------|
| `./data/tlg2001/tlg043/tlg2001.tlg043.opp-grc1.xml` | Deleted  |
| `./data/tlg2001/tlg043/tlg2001.tlg043.opp-lat1.xml` | New      |
| `./data/tlg2001/tlg043/tlg2001.tlg043.opp-lat1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/2313)*

**Comment by capitains-hook** [comment]
## Global

| Changed       |   Status |
|:--------------|---------:|
| `nodes_count` |     +411 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |   -87346 |
| `lat`     |   +87346 |

## Units

| Changed                                             | Status   |
|:----------------------------------------------------|:---------|
| `./data/tlg2001/tlg043/tlg2001.tlg043.opp-grc1.xml` | Deleted  |
| `./data/tlg2001/tlg043/tlg2001.tlg043.opp-lat1.xml` | New      |
| `./data/tlg2001/tlg043/tlg2001.tlg043.opp-lat1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/2314)*

**Pull request merged**
