### PR TITLE
Issue #97, part 2: Deleted Latin language tag in tlg2313.perseus002.perseus-grc1.xml.

### PR DESCRIPTION
**Pull request by jduff-chs**
This is a second pull request to finish closing Issue #97: see Pull Request #245 for more information.

### CODE REVIEW

**Comment by sonofmun** [comment]
I am not touching this one @annettegessner

**Comment by annettegessner** [comment]
Good, @sonofmun, since I fear, the Latin-tag is not deleted yet, but you've only added a nice entry in the revisionDesc, @jduff-chs. ;-)

**Comment by jduff-chs** [comment]
Unsure of how that happened! My mistake, let's try a third time! :)

**Comment by jduff-chs** [comment]
That should do it!

**Comment by annettegessner** [comment]
Wohoo! Gladly merging! 
Issue has already(!) been closed(!) by @sonofmun !!! ;-)

**Comment by sonofmun** [comment]
I close all issues!

**Pull request merged**
