### PR TITLE
Update tlg0708.tlg001.1st1K-grc1.xml

### PR DESCRIPTION
**Pull request by AlisonBabeu**
Upon reviewing again
Added in language tags
Added in file ID.

### CODE REVIEW

**Comment by capitains-hook** [comment]
*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/1640)*

**Comment by planatheisa** [comment]
`"lat"` should be added to `<langUsage>`. Also, why do the tags in `<imprint>` sometimes get translated from latin and sometimes not? 

@AlisonBabeu

**Comment by AlisonBabeu** [comment]
Hi @planatheisa thanks for noting this. In terms of translating the imprint tags, that was something I have done rather consistently when I have been updating headers, but as this header was first updated by someone other than myself I didn't want to change it. Does that make sense?

**Comment by planatheisa** [comment]
It does. I think in this case it really really doesn't matter whether you do one or the other. I was just curious if there was some deep thinking behind it.

**Comment by AlisonBabeu** [comment]
I'm afraid @planatheisa that very few of my metadata decisions involve deep thinking alas. :)

**Comment by capitains-hook** [comment]
*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/1707)*

**Comment by planatheisa** [comment]
:) Oh well. Document is fine, merging now.

**Pull request merged**
