### PR TITLE
Tabea

### PR DESCRIPTION
**Pull request by planatheisa**
issue #136 added sections

### CODE REVIEW

**Comment by annettegessner** [comment]
This file is passing the hook test, but it doesn't find the sections correctly:

RefsDecl parsing passed
1 citation's level found (CORRECT)
Passage level parsing passed
1 found (NOT CORRECT, SHOULD BE ABOUT 347)

Please check this when committing! 
I am not sure about the reason of this, please let me know, if you find out!

Also please use the other way of numbering, described in #136.

**Comment by sonofmun** [comment]
The file now does not pass Hook. There can be no periods in the @n attributes. You need to remove these. For this file, I would simply delete all "p." from the @n, e.g., change "p.24a10" to "24a10". Please make sure you look at Hook and change your files when there is a problem, @planatheisa

**Comment by planatheisa** [comment]
Right now, everything fails. No idea why. Still working on it.

**Comment by planatheisa** [comment]
So, should anyone read this, it failed again but now i know what and will fix it.

**Comment by planatheisa** [comment]
Still working on it. There are duplicates in the numbering, and I'm looking for a way to distinguish them. Apparently, brackets are also forbidden characters.

**Comment by sonofmun** [comment]
Would it work to add an "a" or another letter to the duplicates to distinguish them?

**Comment by planatheisa** [comment]
Did that just now.

**Comment by planatheisa** [comment]
Yay. passes now.

**Comment by sonofmun** [comment]
It passes now. I can't merge from my phone but I will as soon as I get to a computer.

**Pull request merged**
