### PR TITLE
Update tlg0363.tlg007.opp-grc2.xml

### PR DESCRIPTION
**Pull request by AlisonBabeu**
Added in language tagging
Added in file ID
Edited bibliographic info

### CODE REVIEW

**Comment by capitains-hook** [comment]
## Global

| Changed         |   Status |
|:----------------|---------:|
| `coverage`      |    -0.16 |
| `nodes_count`   | -4632    |
| `texts_passing` |    -4    |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |   -54573 |
| `mul`     |   -18265 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg0363/tlg007/tlg0363.tlg007.opp-grc2.xml`   | Failing  |
| `./data/tlg0643/tlg001/tlg0643.tlg001.1st1K-mul1.xml` | Failing  |
| `./data/tlg0643/tlg001/tlg0643.tlg001.1st1K-mul2.xml` | Failing  |
| `./data/tlg2022/tlg003/tlg2022.tlg003.opp-grc1.xml`   | Failing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/1606)*

**Comment by capitains-hook** [comment]
## Global

| Changed         |   Status |
|:----------------|---------:|
| `coverage`      |    -0.07 |
| `nodes_count`   |  -678    |
| `texts_passing` |    -1    |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |   -38588 |

## Units

| Changed                                             | Status   |
|:----------------------------------------------------|:---------|
| `./data/tlg0363/tlg007/tlg0363.tlg007.opp-grc2.xml` | Failing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/1631)*

**Comment by planatheisa** [comment]
There is a `"` missing in `<teiHeader>`.

@AlisonBabeu

**Comment by planatheisa** [comment]
@sonofmun 

The tests are for all files, not just the one pushed, right? I found the fault with tlg0363.tlg007.opp-grc2.xml, but the failed PR-test lists three more documents.

**Comment by sonofmun** [comment]
I only see the one you found for the PR, which failed all of the tests (https://travis-ci.org/OpenGreekAndLatin/First1KGreek/builds/244582471?utm_source=github_status&utm_medium=notification)

**Comment by planatheisa** [comment]
Whoops, order was reversed. My mistake.

**Comment by AlisonBabeu** [comment]
Made the necessary changes hope this is all set.

**Comment by capitains-hook** [comment]
*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/1697)*

**Pull request merged**
