### PR TITLE
issue #157

### PR DESCRIPTION
**Pull request by planatheisa**
First check with Hook.

### CODE REVIEW

**Comment by planatheisa** [comment]
Duplicate references, still working on it.

**Comment by sonofmun** [comment]
I think the best way is to split them and make them two separate citation levels. They refer to the page and the line number on which the text appears. So make the first number a `<div>` and call it @subtype="page" and the second number a `<div>` as the child and make it @subtype="line". I honestly don't know if that matches with the way someone might want to use this text, but it makes sense from a technical and also from a certain humanities point of view.

**Comment by planatheisa** [comment]
Seems a bit of an overkill for text, that is often only a single word, but it makes sense.

**Comment by planatheisa** [comment]
Not passing yet, duplicates and one forbidden character which I must have missed.

**Comment by planatheisa** [comment]
It passes and finds everything, but I'm not entirely sure that it looks how it's supposed to be.

**Comment by sonofmun** [comment]
Now I see what you were talking about, @planatheisa I think that what you did with the TOC is overkill. I would just put all of the `<p>` tags that contain the Greek numerals into one single `<div>`. Then it would look like:

```
<div type="commentary" subtype="TOC" n="1">
    <p>α᾿. Ὅτι οἱ μὲν ἄλλοι Εὐαγγελισταὶ ἐξ αὐτῶν ἄρχονται τῶν ὁ δὲ Ἅγιος Λουκᾶς καὶ προοιμίοις κέχρηται.</p>
    <p>β΄. Περὲ Ζαχαρίου τοῦ πατρὸς τοῦ προδρόμου.</p>
    <p>γ΄. Περὶ τοῦ εὐαγγελισμοῦ.</p>
...
```

I agree with what you said now that I understand what you meant: these do not all need to be in their own `<div>` tags. 
I like how the rest of the text looks, though.

**Comment by planatheisa** [comment]
Alright

**Comment by planatheisa** [comment]
Should be fine now.

**Comment by sonofmun** [comment]
This looks good.

**Pull request merged**
