### PR TITLE
new edition (tlg0081.tlg014.1st1K-grc1.xml)

### LINKED ISSUE #2394: (urn:cts:greekLit:tlg0081.tlg014.1st1K-grc1) new edition
urn:cts:greekLit:tlg0081.tlg014.1st1K-grc1

To access XML files and to see more information, see [Trello Card](https://trello.com/c/Hit8LAWz/14-edit-uc1c020256950-1583112705-dionysius-of-h-opuscula)

### PR DESCRIPTION
**Pull request by charhoughton**
fix #2394 

Used "section" and "subsection" as containers for the fragment sub-divisions--not sure on proper designations.

### CODE REVIEW

**Comment by lcerrato** [comment]
@charhoughton 
Would you like me to finish this now?  I don't want to edit if you're still working on it.

**Comment by charhoughton** [comment]
You're good to work on it

**Comment by lcerrato** [comment]
@charhoughton 
Where did you find pages 218-220? I do not see them in this scan

**Comment by charhoughton** [comment]
The text ends on page 217?

**Comment by lcerrato** [comment]
I could not find the text for 31A, but I think it is just the Hathi was not loading properly. I can see it now

**Pull request merged**
