### PR TITLE
Update tlg1210.tlg002.1st1K-grc1.xml

### PR DESCRIPTION
**Pull request by AlisonBabeu**
Added in author and standardized sourceDesc.
I also shortened the edition title for consistency with the other work.

### CODE REVIEW

**Comment by planatheisa** [comment]
@sonofmun @AlisonBabeu  I think there should be language attributes for `<editor>`, `<author>`, `<title>` and `<imprint>`.

**Comment by AlisonBabeu** [comment]
Hi. I had been under the impression that we weren't adding language attributes to all these elements as it would take a fair amount of time, particularly in terms of all the files that have already been done. In this case, I didn't add the language tag to the editor's name, I just didn't remove it because it was already there and technically correct.  Should I remove it here for consistency rather than adding language tags to all the other elements?

**Comment by sonofmun** [comment]
We need to add the language tags to any elements that do not fit the general language tag for the teiHeader, which should be English. We will then pull this stuff automatically into the metadata for these files. So if we change it here, it should flow to all other places, including (hopefully) the catalog.
In addition to what @planatheisa has mentioned, there should also be an `xml:lang="eng"` attribute on the teiHeader element itself.

**Comment by AlisonBabeu** [comment]
Ah I'm seeing what I missed before that all of those other fields are in Latin, and in general we have left the fields in Latin rather than standardizing them to Teubner, Leipzig, etc. I think I need more coffee. I will add the Latin tags here and try to be consistent in doing so as well as I move forward today.

**Comment by planatheisa** [comment]
That would also be the case for the other pull requests, as far as I have seen.

**Comment by sonofmun** [comment]
Yes, that would be great @AlisonBabeu

**Comment by AlisonBabeu** [comment]
I went back through all of them and think I caught any place where I needed to add in a language tag @sonofmun and @planatheisa

**Pull request merged**
