### PR TITLE
Fixed #129 : (tlg2055.tlg001.perseus-grc1) CapiTains Compliant

### LINKED ISSUE #129: Check citation scheme and refsDecl for /tlg2255/perseus001/tlg2255.perseus001.perseus-grc1.xml

### PR DESCRIPTION
**Pull request by PonteIneptique**
- added seg inside p
- added revisionDesc
- fixed refsDecl
- added del tag for [spurious] text

### CODE REVIEW

**Comment by sonofmun** [comment]
Is there something I need to do here? Or just merge it?

**Comment by PonteIneptique** [comment]
You need to agree with it and merge it :D

**Comment by sonofmun** [comment]
tlg2255.tlg001.perseus-grc1 now passing Hook.  Merging and closing.

**Comment by annettegessner** [comment]
I also thought, there was something specific for Matt to do here, otherwise I would have merged it. ;-)

**Comment by PonteIneptique** [comment]
@annettegessner @sonofmun We actually talked with Matt how I dealt with this one with `seg` instead of div. I wanted to show which one I was talking about. Maybe worth having a look at Annette :dancer:

**Comment by sonofmun** [comment]
What's the deal with the flamenco dancer?

**Comment by PonteIneptique** [comment]
I felt like partying.

**Comment by PonteIneptique** [comment]
:tada:

**Comment by sonofmun** [comment]
Don't we all? And now I understand finally why you assigned this to me.

**Comment by PonteIneptique** [comment]
I

**Pull request merged**
