### PR TITLE
#637: correctes divs, CTS and langUsage, added reference

### PR DESCRIPTION
**Pull request by planatheisa**
First upload, checking hook.

### CODE REVIEW

**Comment by planatheisa** [comment]
Looking good.

**Comment by sonofmun** [comment]
Add `<idno type="filename">`

**Comment by planatheisa** [comment]
@sonofmun There are probably a lot of documents with missing/incorrect idno elements. I could probably write a script to check and correct them.

**Comment by planatheisa** [comment]
Still looking good.

**Comment by sonofmun** [comment]
It shouldn't be too difficult a script to write. If you are interested, go ahead and do it. Though let's get the open PRs merged first, otherwise we will probably get some merge conflicts.

**Pull request merged**
