### PR TITLE
issue #82

### PR DESCRIPTION
**Pull request by planatheisa**
left milestones alone, changed pb-tags, added reference and link to a
scan

### CODE REVIEW

**Comment by annettegessner** [comment]
This "This branch has conflicts that must be resolved" doesn't look good. Can you fix it?

**Comment by planatheisa** [comment]
Is there a way to find out what the conflicts are? Hook just says "failed" on everything. Could it be because of the header?

**Comment by annettegessner** [comment]
What's wrong with the header? Is the file Epidoc-compliant?

Merging conflicts should appear due to different branches having different versions of files. @sonofmun can you help?

**Comment by planatheisa** [comment]
I can't see anything significantly wrong with it. It's just different from most other ones. There are no references to author/editor and suchlike.

**Comment by annettegessner** [comment]
I don't think it's the file itselt that causes the problem, but a conflict in different versions of files in your branches. Did you do something differently while doing these commits?

**Comment by planatheisa** [comment]
It is something with Epidoc probably. I have never had anything to do with that, however.

**Comment by planatheisa** [comment]
No, committed as usual.

**Comment by annettegessner** [comment]
I am not sure, why this file doesn't pass the hook test. Maybe it's the merging conflict and not the file itselt, that causes this. 
Oxygen will tell you, if there is a problem with the Epidoc compliance. If it's "green", the problem lies elsewhere.

**Comment by planatheisa** [comment]
It's green. No problem there.

**Pull request closed without merging**
