### PR TITLE
Tabea #496

### PR DESCRIPTION
**Pull request by planatheisa**
First upload, checking hook.

### CODE REVIEW

**Comment by planatheisa** [comment]
There is a chapter in this work, that says (in Greek) "chapter 6 and 7". How can I put this in the `@n` of the div? Putting `n="6-7"` doesn't work (should have known that...). See: [https://babel.hathitrust.org/cgi/pt?id=hvd.hxpp8u;view=1up;seq=245](url) for reference. @annettegessner @sonofmun

**Comment by sonofmun** [comment]
This is a really good question. Any ideas @PonteIneptique ? I will bring it up at the OGL meeting this afternoon.

**Comment by PonteIneptique** [comment]
I can't see the original unfortunately. Make it 6 for the moment if you need. Best thing would be to search where the division takes place in other editions :)

**Comment by sonofmun** [comment]
The weird thing is that what follows is a single sentence in Greek in square brackets. It's almost like it isn't part of the text as it exists but a summary of these two sections from somewhere else. I don't know enough about Galen to know how to deal with this.

**Comment by annettegessner** [comment]
Matt and I just opened a new issue to discuss things like that: see #614 Use of <div type="commentary" ...>

**Comment by planatheisa** [comment]
I changed it to "6" and it passes now.

**Pull request merged**
