### PR TITLE
Added tlg0093.ogl002.1st1K-grc1.xml

### PR DESCRIPTION
**Pull request by sonofmun**
Theophrastus Concerning Weather Signs

### CODE REVIEW

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +2 |
| `metadata_total`   |       +2 |
| `nodes_count`      |      +61 |
| `texts_passing`    |       +1 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |    +3743 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg0093/__cts__.xml`                          | New      |
| `./data/tlg0093/ogl002/__cts__.xml`                   | New      |
| `./data/tlg0093/ogl002/tlg0093.ogl002.1st1K-grc1.xml` | New      |
| `./data/tlg0093/__cts__.xml`                          | Passing  |
| `./data/tlg0093/ogl002/__cts__.xml`                   | Passing  |
| `./data/tlg0093/ogl002/tlg0093.ogl002.1st1K-grc1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/2238)*

**Comment by AlisonBabeu** [comment]
Hi @sonofmun and @annettegessner I have one comment regarding this ID. I had cataloged this work under the Theophrastus Fragmenta ID, De Signis Tempestum [tlg0093.tlg010x03](http://catalog.perseus.org/catalog/urn:cts:greekLit:tlg0093.tlg010x03). I'm not sure this matters but I wasn't sure if you wanted to use the same ID rather than creating a new OGL one for this work.

**Comment by sonofmun** [comment]
See my comment on #1686

**Comment by AlisonBabeu** [comment]
And I replied on #1686!

**Comment by sonofmun** [comment]
Nice catch with the filename. Corrected and testing.

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +1 |
| `metadata_total`   |       +1 |
| `nodes_count`      |      +61 |
| `texts_passing`    |       +1 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |    +3743 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg0093/ogl002/__cts__.xml`                   | New      |
| `./data/tlg0093/ogl002/tlg0093.ogl002.1st1K-grc1.xml` | New      |
| `./data/tlg0093/ogl002/__cts__.xml`                   | Passing  |
| `./data/tlg0093/ogl002/tlg0093.ogl002.1st1K-grc1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/2305)*

**Pull request merged**
