### PR TITLE
Added Iliad Scholia

### PR DESCRIPTION
**Pull request by sonofmun**
This PR was reverted about a month ago and I am not sure why. This is a really large XML file, so maybe it was causing problems (although I hope that I have fixed those).

### CODE REVIEW

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +4 |
| `metadata_total`   |       +4 |
| `nodes_count`      |   +24947 |
| `texts_passing`    |       +4 |
| `texts_total`      |       +4 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |  +826678 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg0592/tlg002/__cts__.xml`                   | New      |
| `./data/tlg0592/tlg002/tlg0592.tlg002.1st1K-grc1.xml` | New      |
| `./data/tlg0592/tlg004/__cts__.xml`                   | New      |
| `./data/tlg0592/tlg004/tlg0592.tlg004.1st1K-grc1.xml` | New      |
| `./data/tlg0592/tlg005/__cts__.xml`                   | New      |
| `./data/tlg0592/tlg005/tlg0592.tlg005.1st1K-grc1.xml` | New      |
| `./data/tlg5026/tlg001/__cts__.xml`                   | New      |
| `./data/tlg5026/tlg001/tlg5026.tlg001.1st1K-grc1.xml` | New      |
| `./data/tlg0592/tlg002/__cts__.xml`                   | Passing  |
| `./data/tlg0592/tlg002/tlg0592.tlg002.1st1K-grc1.xml` | Passing  |
| `./data/tlg0592/tlg004/__cts__.xml`                   | Passing  |
| `./data/tlg0592/tlg004/tlg0592.tlg004.1st1K-grc1.xml` | Passing  |
| `./data/tlg0592/tlg005/__cts__.xml`                   | Passing  |
| `./data/tlg0592/tlg005/tlg0592.tlg005.1st1K-grc1.xml` | Passing  |
| `./data/tlg5026/tlg001/__cts__.xml`                   | Passing  |
| `./data/tlg5026/tlg001/tlg5026.tlg001.1st1K-grc1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/3121)*

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +4 |
| `metadata_total`   |       +4 |
| `nodes_count`      |   +24947 |
| `texts_passing`    |       +4 |
| `texts_total`      |       +4 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |  +826678 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg0592/tlg002/__cts__.xml`                   | New      |
| `./data/tlg0592/tlg002/tlg0592.tlg002.1st1K-grc1.xml` | New      |
| `./data/tlg0592/tlg004/__cts__.xml`                   | New      |
| `./data/tlg0592/tlg004/tlg0592.tlg004.1st1K-grc1.xml` | New      |
| `./data/tlg0592/tlg005/__cts__.xml`                   | New      |
| `./data/tlg0592/tlg005/tlg0592.tlg005.1st1K-grc1.xml` | New      |
| `./data/tlg5026/tlg001/__cts__.xml`                   | New      |
| `./data/tlg5026/tlg001/tlg5026.tlg001.1st1K-grc1.xml` | New      |
| `./data/tlg0592/tlg002/__cts__.xml`                   | Passing  |
| `./data/tlg0592/tlg002/tlg0592.tlg002.1st1K-grc1.xml` | Passing  |
| `./data/tlg0592/tlg004/__cts__.xml`                   | Passing  |
| `./data/tlg0592/tlg004/tlg0592.tlg004.1st1K-grc1.xml` | Passing  |
| `./data/tlg0592/tlg005/__cts__.xml`                   | Passing  |
| `./data/tlg0592/tlg005/tlg0592.tlg005.1st1K-grc1.xml` | Passing  |
| `./data/tlg5026/tlg001/__cts__.xml`                   | Passing  |
| `./data/tlg5026/tlg001/tlg5026.tlg001.1st1K-grc1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/3123)*

**Comment by sonofmun** [comment]
Nice catch, @planatheisa . I have changed the URL for volume 6.

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       -1 |
| `metadata_total`   |       -1 |
| `nodes_count`      |   +24527 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |  +761395 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg2233/__cts__.xml`                          | Deleted  |
| `./data/tlg2233/tlg001/__cts__.xml`                   | Deleted  |
| `./data/tlg2233/tlg001/tlg2233.tlg001.1st1K-grc1.xml` | Deleted  |
| `./data/tlg5026/tlg001/__cts__.xml`                   | New      |
| `./data/tlg5026/tlg001/tlg5026.tlg001.1st1K-grc1.xml` | New      |
| `./data/tlg5026/tlg001/__cts__.xml`                   | Passing  |
| `./data/tlg5026/tlg001/tlg5026.tlg001.1st1K-grc1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/3197)*

**Pull request merged**
