### PR TITLE
Issue 1552- OCR corrections in Lucian

### PR DESCRIPTION
**Pull request by LindaMcNulty**
plus addition of missing lang tags

### CODE REVIEW

**Comment by sonofmun** [comment]
Your OCR corrections look fine but you also have some files in this pull request for which I requested changes in another pull request. You will need to make the changes to those files on that branch and then merge your changes from that branch into this branch.
To avoid this in the future, you should always create new branches for your issues from the master branch and not from the branch for another issue. Otherwise, all of the changes that you made for that issue will be included in your new branch.
Let me know if you need help doing this.

**Comment by LindaMcNulty** [comment]
Duly noted! Which files from which other pull request are present in this one?

**Comment by sonofmun** [comment]
The files for tlg0057.tlg095 and tlg0057.tlg096 from pull request #1547 on branch issue-837 are the ones that have made it into this pull request.

**Comment by LindaMcNulty** [comment]
Those files have been updated now!

**Pull request merged**
