### PR TITLE
Added Hosea

### PR DESCRIPTION
**Pull request by sonofmun**

### CODE REVIEW

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +1 |
| `metadata_total`   |       +1 |
| `nodes_count`      |     +211 |
| `texts_passing`    |       +1 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |    +3920 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg0527/tlg036/__cts__.xml`                   | New      |
| `./data/tlg0527/tlg036/tlg0527.tlg036.1st1K-grc1.xml` | New      |
| `./data/tlg0527/tlg036/__cts__.xml`                   | Passing  |
| `./data/tlg0527/tlg036/tlg0527.tlg036.1st1K-grc1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/2908)*

**Comment by capitains-hook** [comment]
## Global

| Changed            |   Status |
|:-------------------|---------:|
| `metadata_passing` |       +1 |
| `metadata_total`   |       +1 |
| `nodes_count`      |     +211 |
| `texts_passing`    |       +1 |
| `texts_total`      |       +1 |

## Words

| Changed   |   Status |
|:----------|---------:|
| `grc`     |    +3920 |

## Units

| Changed                                               | Status   |
|:------------------------------------------------------|:---------|
| `./data/tlg0527/tlg036/__cts__.xml`                   | New      |
| `./data/tlg0527/tlg036/tlg0527.tlg036.1st1K-grc1.xml` | New      |
| `./data/tlg0527/tlg036/__cts__.xml`                   | Passing  |
| `./data/tlg0527/tlg036/tlg0527.tlg036.1st1K-grc1.xml` | Passing  |

*[Hook UI build recap](http://ci.perseids.org/repo/OpenGreekAndLatin/First1KGreek/2975)*

**Comment by planatheisa** [comment]
@sonofmun Test did not complete. Should I merge anyway?

**Comment by sonofmun** [comment]
I restarted the build. Hopefully it will complete this time.

**Pull request merged**
